In [17]:
import numpy as np
from sympy import *
from IPython.display import display, Math

1. 
Recall that the hyperbolic sine, denoted by sinh, is $\displaystyle\sinh(x)=\frac{\exp(x)−\exp(−x)}{2}$                      
Write a function `my_sinh(x)` where the output y is the hyperbolic sine computed on x. Assume that x is a 1 by 1 float.        
Test Cases:                                                                                                                       
In: my_sinh(0)                                                                                                                  
Out: 0                                                                                                                                    
In: my_sinh(1)                                                                                                                
Out: 1.1752                                                                                                                     
In: my_sinh(2)                                                                                                                
Out: 3.6269

In [2]:
def my_sinh(x):
    y=(np.exp(x)-np.exp(-x))*0.5
    return y

In [3]:
my_sinh(0)

0.0

In [4]:
my_sinh(1)

1.1752011936438014

In [5]:
my_sinh(2)

3.626860407847019

2. Write a function `my_checker_board(n)` where the output m is an n×n array with the following form:

$\qquad\qquad m =\begin{matrix} 1& 0& 1& 0& 1 \\ 0& 1& 0& 1& 0\\ 1& 0& 1& 0& 1\\ 0& 1& 0& 1& 0\\ 1& 0& 1& 0& 1 \end{matrix}$

Note that the upper-left element should always be 1. Assume that n is a strictly positive integer.                            
Test Cases:                                                                                                                    
In: my_checker_board(1)                                                                                                      
Out: 1                                                                                                                       

In: my_checker_board(2)                                                                                                         
Out: array([[1, 0],                                                                                                               
$\qquad \ \ \ \quad$[0, 1]])


In: y = my_checker_board(3)                                                                                                                  
Out: array([[1, 0, 1],                                                                                                           
$\qquad \ \ \ \quad$[0, 1, 0],                                                                                                       
$\qquad \ \ \ \quad$[1, 0, 1]])

In: y = my_checker_board(5)                                                                                                               
Out: array([[1, 0, 1, 0, 1],                                                                                                  
$\qquad \ \ \ \quad$[0, 1, 0, 1, 0],                                                                                                
$\qquad \ \ \ \quad$[1, 0, 1, 0, 1],                                                                                             
$\qquad \ \ \ \quad$[0, 1, 0, 1, 0],                                                                                          
$\qquad \ \ \ \quad$[1, 0, 1, 0, 1]])       

In [6]:
def my_checker_board(n):
    m = np.zeros((n, n), dtype=int)  # Initialize an n×n array filled with zeros
    m[::2, ::2] = 1  # Set elements at even row and even column indices to 1
    m[1::2, 1::2] = 1  # Set elements at odd row and odd column indices to 1
    return m

In [7]:
my_checker_board(1)

array([[1]])

In [8]:
my_checker_board(2)

array([[1, 0],
       [0, 1]])

In [9]:
my_checker_board(3)

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]])

In [10]:
my_checker_board(5)

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

3. 
Write a function `my_triangle(b,h)` where the output is the area of a triangle with base, b, and height, h.              
Recall that the area of a triangle is one-half the base times the height. Assume that b and h are just 1 by 1 float numbers. 

Test Cases:                                                                                                                 

In: my_triangle(1, 1)                                                                                                        
Out: 0.5                                                                                                                     

In: my_triangle(2, 1)                                                                                                             
Out: 1                                                                                                                       

In: my_triangle(12, 5)                                                                                                           
Out: 30

In [11]:
def my_triangle(b, h):
    area = 0.5 * b * h  # Calculate the area of the triangle
    return area

In [12]:
my_triangle(1, 1)

0.5

In [13]:
my_triangle(2, 1)

1.0

In [14]:
my_triangle(12, 5)

30.0

4. 
Write a function `my_split_matrix(m)`, where m is an array, the output is a list [m1, m2] where m1 is the left half of m, and m2 is the right half of m.                                                                                             
In the case where there is an odd number of columns, the middle column should go to m1. Assume that m has at least two columns.

Test Cases:

In: m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])                                                                             
In: m1, m2 = my_split_matrix(m)                                                                                                 
Out: m1 =$\ $array([[1, 2],                                                                                                           
$\qquad\qquad\quad \ \ \ $[4, 5],                                                                                                
$\qquad\qquad\quad \ \ \ $[7, 8]])                                                                                                   
Out: m2 = array([3, 6, 9])                                                                                                       

In: m = np.ones((5, 5))                                                                                                           
In: m1, m2 = my_split_matrix(m)                                                                                               
Out: m1 = array([[1., 1., 1.],                                                                                                     
$\qquad\qquad\quad \ \ \ $[1., 1., 1.],                                                                                                                
$\qquad\qquad\quad \ \ \ $[1., 1., 1.],                                                                                                                
$\qquad\qquad\quad \ \ \ $[1., 1., 1.],                                                                                                                
$\qquad\qquad\quad \ \ \ $[1., 1., 1.]])                                                                                                                
Out: m2 = array([[1., 1.],                                                                                                                
$\qquad\qquad\quad \ \ \ $[1., 1.],                                                                                                                    
$\qquad\qquad\quad \ \ \ $[1., 1.],                                                                                                                    
$\qquad\qquad\quad \ \ \ $[1., 1.],                                                                                                                    
$\qquad\qquad\quad \ \ \ $[1., 1.]])

In [20]:
def my_split_matrix(m):
    rows, columns = m.shape  # Get the number of rows and columns in the matrix 
    split_index = columns // 2 + columns % 2     # Calculate the index to split the columns

    # Split the matrix into left and right halves
    m1 = m[:, :split_index]
    m2 = m[:, split_index:]
    display(Math('m_1='+latex(Matrix(m1))+'m_2='+latex(Matrix(m2))))
    return [m1, m2]

In [21]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m1, m2 = my_split_matrix(m)

<IPython.core.display.Math object>

In [22]:
m = np.ones((5, 5))
m1, m2 = my_split_matrix(m)

<IPython.core.display.Math object>

5. Write a function `my_cylinder(r,h)`, where r and h are the radius and height of a cylinder, respectively, and the output is a list [s, v] where s and v are the surface area and volume of the same cylinder, respectively. Recall that the surface area of a cylinder is $2\pi r^2+ 2\pi rh,$ and the volume is $\pi r^2 h$. Assume that r and h are 1 by 1 floats.

Test Cases:                                                                                                                      
In: my_cylinder(1,5)                                                                                                             
Out: [37.6991, 15.7080]                                                                                                     

In [28]:
def my_cylinder(r, h):
    s = (2 * np.pi * r**2) + (2 * np.pi * r * h)
    v = np.pi * r**2 * h
    return [s, v]

In [29]:
my_cylinder(1,5)

[37.69911184307752, 15.707963267948966]

6. Write a function my_n_odds(a), where a is a one-dimensional array of floats and the output is the number of odd numbers in a.

Test Cases:                                                                                                                 

In: my_n_odds(np.arange(100))                                                                                                       
Out: 50                                                                                                                     

In: my_n_odds(np.arange(2, 100, 2))                                                                                               
Out: 0

In [33]:
def my_n_odds(a):
    odds = np.count_nonzero(a % 2 != 0)  # Count the number of non-zero remainders when divided by 2
    return odds

In [34]:
my_n_odds(np.arange(100))

50

In [35]:
my_n_odds(np.arange(2, 100, 2))

0

7. Write a function my_twos(m,n) where the output is an m×n array of twos. Assume that m and n are strictly positive integers.

Test Cases:

In: my_twos(3, 2)                                                                                                               
Out:$ \ \ $ array([[2, 2],                                                                                                                
$\qquad \ \qquad$[2, 2],                                                                                                                              
$\qquad \ \qquad$[2, 2]])                                                                                                                     

In: my_twos(1, 4)                                                                                                                
Out: array([2, 2, 2, 2])

In [36]:
def my_twos(m, n):
    return np.full((m, n), 2)  # Create an m×n array filled with twos

In [37]:
my_twos(3, 2)

array([[2, 2],
       [2, 2],
       [2, 2]])

In [38]:
my_twos(1, 4)

array([[2, 2, 2, 2]])

8. Write a lambda function that takes in input x and y, and the output is the value of x - y.

In [39]:
subtract = lambda x, y: x - y
subtract(5, 3)

2

9. Write a function add_string(s1, s2) where the output is the concatenation of the strings s1 and s2.  

Test Cases: 

In: s1 = add_string("Programming", " ")                                                                                              
In: s2 = add_string("is ", "fun!")                                                                                                 
In: add_string(s1, s2)                                                                                                                                                                                          
Out: "Programming is fun!"

In [43]:
def add_string(s1, s2):
    return s1 + s2  # Concatenate the strings using the + operator 

s1 = add_string("Programming", " ")
s2 = add_string("is ", "fun!")
add_string(s1, s2)

'Programming is fun!'

10. Generate the following errors:                                                                                                  
• TypeError: fun() missing 1 required positional argument: "a"                                                                                                
• IndentationError: expected an indented block

In [44]:
def fun(a):
    print(a)

fun()

TypeError: fun() missing 1 required positional argument: 'a'

In [45]:
if True:
print("Hello, World!")

IndentationError: expected an indented block after 'if' statement on line 1 (1831089614.py, line 2)

11. Write a function greeting(name, age) where name is a string, age is a float, and the output is a string "Hi, my name is XXX and I am XXX years old." where XXX are the input name and age, respectively.

Test Cases:

In: greeting("John", 26)                                                                                                             
Out: "Hi, my name is John and I am 26 years old."

In: greeting("Kate", 19)                                                                                                             
Out: "Hi, my name is Kate and I am 19 years old."

In [46]:
def greeting(name, age):
    greeting_string = "Hi, my name is {} and I am {} years old.".format(name, age)
    return greeting_string

In [47]:
greeting("John", 26)

'Hi, my name is John and I am 26 years old.'

In [48]:
greeting("Kate", 19)

'Hi, my name is Kate and I am 19 years old.'

12. Let r1 and r2 be the radius of circles with the same center and let r2 > r1.                                         
Write a function `my_donut_area(r1, r2)` where the output is the area outside of the circle with radius r1 and inside the circle with radius r2.                                                                                                    
Make sure that the function is vectorized. Assume that r1 and r2 are one-dimensional arrays of the same size.

Test Cases:                                                                                                                        
In: my_donut_area(np.arange(1, 4), np.arange(2, 7, 2))                                                                                                                        
Out: array([9.4248, 37.6991, 84.8230])

In [50]:
def my_donut_area(r1, r2):
    return np.pi * (r2**2 - r1**2)

my_donut_area(np.arange(1, 4), np.arange(2, 7, 2))

array([ 9.42477796, 37.69911184, 84.82300165])

13. Write a function `my_within_tolerance(A, a, tol)` where the output is an array or list of the indices in A such that |A − a| < tol.                                                                                                                
Assume that A is a one-dimensional float list or array, and that a and tol are 1 by 1 floats.

Test Cases:                                                                                                                

In: my_within_tolerance([0, 1, 2, 3], 1.5, 0.75)                                                                                                                
Out: [1, 2]                                                                                                                


In: my_within_tolerance(np.arange(0, 1.01, 0.01), 0.5, 0.03)                                                                                                                
Out: [47, 48, 49, 50, 51, 52]

In [53]:
def my_within_tolerance(A, a, tol):
    indices = [i for i, val in enumerate(A) if abs(val - a) < tol]
    return indices

In [54]:
my_within_tolerance([0, 1, 2, 3], 1.5, 0.75)

[1, 2]

In [55]:
my_within_tolerance(np.arange(0, 1.01, 0.01), 0.5, 0.03)

[47, 48, 49, 50, 51, 52]

14. 
Write a function `bounding_array(A, top, bottom)` where the output is equal to the array A wherever bottom < A < top,     
the output is equal to bottom wherever A <= bottom, and the output is equal to top wherever A >= top.                   
Assume that A is a one-dimensional float array and that top and bottom are 1 by 1 floats.

Test Cases:                                                                                                                  
In: bounding_array(np.arange(-5, 6, 1), 3, -3)                                                                                  
Out: [-3, -3, -3, -2, -1, 0, 1, 2, 3, 3, 3]

In [56]:
def bounding_array(A, top, bottom):
    return np.where(A < bottom, bottom, np.where(A > top, top, A))

bounding_array(np.arange(-5, 6, 1), 3, -3)

array([-3, -3, -3, -2, -1,  0,  1,  2,  3,  3,  3])