## 1. Create a list and save it in a text file that each of the item in the list will take one line.

In [1]:
# Example list
my_list = ['Apple', 'Banana', 'Orange', 'Mango']

# Define the file path
file_path = 'list_items.txt'

# Open the file in write mode
with open(file_path, 'w') as file:
    # Write each item in the list to a new line
    for item in my_list:
        file.write(item + '\n')

In [2]:
file=open('list_items.txt',"r")

print(file.read())
print()

Apple
Banana
Orange
Mango




## 2. Save the same list in problem 1 to a CSV file.

In [3]:
import csv

# Example list
my_list = ['Apple', 'Banana', 'Orange', 'Mango']

# Define the file path
file_path = 'list_items.csv'

# Open the file in write mode
with open(file_path, 'w', newline='') as file:
    # Create a CSV writer object
    writer = csv.writer(file)

    # Write each item in the list as a row
    for item in my_list:
        writer.writerow([item])

In [4]:
# Create an empty list to store the data
data = []

# Open the CSV file
with open(file_path, "r") as file:
    # Create a CSV reader object
    reader = csv.reader(file)
    
    # Iterate over each row in the CSV file
    for row in reader:
        # Append each row to the data list
        data.append(row)

# Print the data
for row in data:
    print(row)

['Apple']
['Banana']
['Orange']
['Mango']


In [5]:
import pandas as pd

pd.read_csv('list_items.csv')

Apple
0  Banana
1  Orange
2   Mango

## 3. Create a 2D numpy array, and save it to CSV file and read it back to a 2D array.

In [6]:
import numpy as np

# Create a 2D array
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Define the file path
file_path = 'array_data.csv'

# Save the array to a CSV file
with open(file_path, 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerows(my_array)

# Read the CSV file back into a 2D array
read_array = np.genfromtxt(file_path, delimiter=',')

# Print the original and read arrays
print("Original array:")
print(my_array)
print("\nRead array:")
print(read_array)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Read array:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## 4. Save the same array in problem 2 to a pickle file and load it back.

In [7]:
import pickle

# Create a 2D array
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Define the file path
file_path = 'array_data.pickle'

# Save the array to a pickle file
with open(file_path, 'wb') as file:
    pickle.dump(my_array, file)

# Load the pickle file back into a 2D array
with open(file_path, 'rb') as file:
    loaded_array = pickle.load(file)

# Print the original and loaded arrays
print("Original array:")
print(my_array)
print("\nLoaded array:")
print(loaded_array)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Loaded array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 5. Create a dictionary and save it to a JSON file.

In [8]:
import json

# Create a dictionary
my_dict = {
            "name": "John Doe",
            "age": 30,
            "city": "New York"
          }

# Define the file path
file_path = 'dictionary_data.json'

# Save the dictionary to a JSON file
with open(file_path, 'w') as file:
    json.dump(my_dict, file)

In [9]:
with open(file_path, "r") as file:
    loaded_data = json.load(file)

# Convert the loaded data to a string
json_string = json.dumps(loaded_data, indent=4)

# Print the JSON string
print(json_string)

{
    "name": "John Doe",
    "age": 30,
    "city": "New York"
}


## 6. Create a 1D numpy array, and save it to a JSON file with the key named ‘data’.        
## $ \ \ \$ Then load it back.

In [10]:
# Create a 1D NumPy array
my_array = np.array([1, 2, 3, 4, 5])

# Convert the array to a Python list
data = my_array.tolist()

# Create a dictionary with the array data
data_dict = {"data": data}

# Define the file path
file_path = "array_data.json"

# Save the data dictionary to a JSON file
with open(file_path, "w") as file:
    json.dump(data_dict, file)

# Load the JSON file and retrieve the array
with open(file_path, "r") as file:
    loaded_data = json.load(file)
    loaded_array = np.array(loaded_data["data"])

print("Loaded Array:", loaded_array)

Loaded Array: [1 2 3 4 5]
