1. Assign the value 2 to the variable x and the value 3 to the variable y. Clear just the variable x.

In [1]:
x=2
y=3
x,y

(2, 3)

Write a line of code that generates the following error:

     NameError: name "x" is not defined

In [2]:
del x

In [3]:
x

NameError: name 'x' is not defined

3. Let x = 10 and y = 3. Write a line of code that will make each of the following assignments.                                  
`u = x + y`                                                                                                                       
`v = xy`                                                                                                                            
`w = x/y`                                                                                                                        
`z = sin(x)`                                                                                                                         
`r = 8sin(x)`                                                                                                                   
`s = 5sin(xy)`                                                                                                                    
`p = x**y`

In [4]:
from pylab import *
x=10
y=3
u = x + y
v = x*y
w = x/y
z = sin(x)
r = 8*sin(x) 
s = 5*sin(x*y)
p = x**y

print('u=',u,'\nv=',v,'\nw=',w,'\nz=',z,'\nr=',r,'\ns=',s,'\np=',p)

u= 13 
v= 30 
w= 3.3333333333333335 
z= -0.5440211108893698 
r= -4.352168887114958 
s= -4.940158120464309 
p= 1000


4. Show all the variables in the Jupyter notebook after you finish Problem 3.

5. Assign string "123" to the variable S. Convert the string into a float type and assign the output to the variable N.          
Verify that S is a string and N is a float using the type function.

In [5]:
S='123'
N=float(S)
type(S),type(N)

(str, float)

6. Assign the string "HELLO" to the variable s1 and the string "hello" to the variable s2.                                
Use the == operator to show that they are not equal. Use the == operator to show that s1 and s2 are equal if the lower method is used on s1.                                                                                                     
Use the == operator to show that s1 and s2 are equal if upper method is used on s2.

In [6]:
s1='HELLO'
s2='hello'

print(s1==s2)
print(s1.lower()==s2)
print(s1==s2.upper())

False
True
True


7. Use the print function to generate the following strings:                                                                     
• The world "Engineering" has 11 letters.                                                                                      
• The word "Book" has 4 letters.

In [7]:
n= 'Engineering'
l=len(n)
print('The world %s has %i letters'%(n,l))

The world Engineering has 11 letters


8. Check if "Python" is in "Python is great!".

In [8]:
sentence = 'Python is great!'
word = 'Python'

if word in sentence:
    print('Word found.')

Word found.


9. Get the last word "great" from "Python is great!"

In [9]:
words = sentence.split()
print(words[-1])

great!


10. Assign list [1, 8, 9, 15] to a variable list_a and insert 2 at index 1 using the insert method.                              
Append 4 to the list_a using the append method.

In [10]:
list_a=[1, 8, 9, 15] 

list_a.insert(1,2)

print(list_a)

list_a.append(4)

print(list_a)

[1, 2, 8, 9, 15]
[1, 2, 8, 9, 15, 4]


11. Sort the list_a in problem 10 in ascending order.

In [11]:
list_a.sort()
print(list_a)

[1, 2, 4, 8, 9, 15]


12. Turn "Python is great!" into a list.

In [12]:
list(sentence.split(" "))

['Python', 'is', 'great!']

13. Create one tuple with element "One", 1 and assign it to tuple_a.

In [13]:
tuple_a = ("One", 1)
tuple_a

('One', 1)

14. Get the second element in the tuple_a in Problem 13.

In [14]:
tuple_a[1]

1

15. Get the unique element from (2, 3, 2, 3, 1, 2, 5).

In [15]:
tuple_values = (2, 3, 2, 3, 1, 2, 5)
set(tuple_values)

{1, 2, 3, 5}

16. Assign (2, 3, 2) to set_a, and (1, 2, 3) to set_b. Obtain the following:                                                     
• union of set_a and set_b                                                                                                      
• intersection of set_a and set_b                                                                                            
• difference of set_a to set_b using difference method

In [16]:
set_a = {2, 3, 2}
set_b = {1, 2, 3}

In [17]:
set_a.union(set_b)

{1, 2, 3}

In [18]:
set_a.intersection(set_b)

{2, 3}

In [19]:
set_a.difference(set_b)

set()

17. Create a dictionary that has the keys "A", "B", "C" with values "a", "b", "c" individually. Print all the keys in the dictionary

In [20]:
my_dict = {"A": "a", "B": "b", "C": "c"}

for key in my_dict.keys():
    print(key)

A
B
C


18. Check if key "B" is in the dictionary defined in Problem 17

In [21]:
if "B" in my_dict:
    print("Key 'B' is present in the dictionary.")
else:
    print("Key 'B' is not present in the dictionary.")

Key 'B' is present in the dictionary.


19. Create array x and y, where x = [1, 4, 3, 2, 9, 4] and y=[2, 3, 4, 1, 2, 3]. Compute the assignments from Problem 3.

In [23]:
x = [1, 4, 3, 2, 9, 4] 
y = [2, 3, 4, 1, 2, 3]

def fncn(x,y):
    u = x + y
    v = x*y
    w = x/y
    z = sin(x)
    r = 8*sin(x) 
    s = 5*sin(x*y)
    p = x**y
    print('x=',x,'y=',y,'u=',u,'v=',v,'w=',w,'z=',z,'r=',r,'s=',s,'p=',p,'\n')
    
for i,j in zip(x,y):
    fncn(i,j)

x= 1 y= 2 u= 3 v= 2 w= 0.5 z= 0.8414709848078965 r= 6.731767878463172 s= 4.546487134128409 p= 1 

x= 4 y= 3 u= 7 v= 12 w= 1.3333333333333333 z= -0.7568024953079282 r= -6.054419962463426 s= -2.6828645900021746 p= 64 

x= 3 y= 4 u= 7 v= 12 w= 0.75 z= 0.1411200080598672 r= 1.1289600644789377 s= -2.6828645900021746 p= 81 

x= 2 y= 1 u= 3 v= 2 w= 2.0 z= 0.9092974268256817 r= 7.274379414605454 s= 4.546487134128409 p= 2 

x= 9 y= 2 u= 11 v= 18 w= 4.5 z= 0.4121184852417566 r= 3.2969478819340527 s= -3.754936233858381 p= 81 

x= 4 y= 3 u= 7 v= 12 w= 1.3333333333333333 z= -0.7568024953079282 r= -6.054419962463426 s= -2.6828645900021746 p= 64 



20. Generate an array with size 100 evenly spaced between −10 to 10 using linspace function in NumPy

In [24]:
np.linspace(-10, 10, 100)

array([-10.        ,  -9.7979798 ,  -9.5959596 ,  -9.39393939,
        -9.19191919,  -8.98989899,  -8.78787879,  -8.58585859,
        -8.38383838,  -8.18181818,  -7.97979798,  -7.77777778,
        -7.57575758,  -7.37373737,  -7.17171717,  -6.96969697,
        -6.76767677,  -6.56565657,  -6.36363636,  -6.16161616,
        -5.95959596,  -5.75757576,  -5.55555556,  -5.35353535,
        -5.15151515,  -4.94949495,  -4.74747475,  -4.54545455,
        -4.34343434,  -4.14141414,  -3.93939394,  -3.73737374,
        -3.53535354,  -3.33333333,  -3.13131313,  -2.92929293,
        -2.72727273,  -2.52525253,  -2.32323232,  -2.12121212,
        -1.91919192,  -1.71717172,  -1.51515152,  -1.31313131,
        -1.11111111,  -0.90909091,  -0.70707071,  -0.50505051,
        -0.3030303 ,  -0.1010101 ,   0.1010101 ,   0.3030303 ,
         0.50505051,   0.70707071,   0.90909091,   1.11111111,
         1.31313131,   1.51515152,   1.71717172,   1.91919192,
         2.12121212,   2.32323232,   2.52525253,   2.72

21. Let array_a be an array [-1, 0, 1, 2, 0, 3]. Write a command that will return an array consisting of all the elements of array_a that are larger than zero.                                                                                        
Hint: Use logical expression as the index of the array

In [25]:
array_a = np.array([-1, 0, 1, 2, 0, 3])

array_a[array_a > 0]

array([1, 2, 3])

22. Create an array $ y=\begin{pmatrix} 3 & 5 & 3 \\ 2 & 2 & 5 \\ 3 & 8 & 9 \end{pmatrix}$ and calculate its transpose.

In [27]:
y = np.array([[3,5,3],
              [2,2,5],
              [3,8,9]])
np.transpose(y)

array([[3, 2, 3],
       [5, 2, 8],
       [3, 5, 9]])

23. Create a 2×4 zero array.

In [29]:
A=np.zeros((2, 4))
A

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

24. Change the second column in the above array to 1.

In [30]:
A[:, 1] = 1
A

array([[0., 1., 0., 0.],
       [0., 1., 0., 0.]])

25. Write a magic command to clear all the variables in the Jupyter notebook.

In [36]:
%reset -f