## $$\text{Linear Algebra}$$

Q1.Using **Gauss elimination method** to form a upper triangulation of matrix .
       
And find the **determinant** by multiplying its diagonal and check using **$\text{np.linalg.det()}$**

In [1]:
import numpy as np
def gauss(a):
    m, n = a.shape               
    augment_mat = a
    np.set_printoptions(precision = 2, suppress = True)
    print('$ Original augment matrix $')
    print(augment_mat,'\n')
    print('# starting the elimination of matrix ') 
    
    for k in range(n):                        
        for j in range(k+1,n):                      
            q = float(augment_mat[j][k]) / augment_mat[k][k]  # lambda
            for m in range(k, n): 
                augment_mat[j][m] -=  q * augment_mat[k][m]
                 
    print('^^ this is the outstanding matrix from Gauss elimation ^^')           
    print(augment_mat,'\n')
    M = 1        
    for i in range(n):
        M *= augment_mat[i][i]
    print('Determinant of the matrix is :',M)
    return None

In [2]:
A = np. array([[ 1., 2.,-1., 1.],
               [-1., 1., 2.,-1.],
               [ 2.,-1., 2., 2.],
               [ 1., 1.,-1., 2.]])

print('\nGaussian elimination:  ')
gauss(A)
print('****************************************')
print('using np.linalg.det() :',np.linalg.det(A))
print('****************************************')


Gaussian elimination:  
$ Original augment matrix $
[[ 1.  2. -1.  1.]
 [-1.  1.  2. -1.]
 [ 2. -1.  2.  2.]
 [ 1.  1. -1.  2.]] 

# starting the elimination of matrix 
^^ this is the outstanding matrix from Gauss elimation ^^
[[ 1.    2.   -1.    1.  ]
 [ 0.    3.    1.    0.  ]
 [ 0.    0.    5.67  0.  ]
 [ 0.    0.    0.    1.  ]] 

Determinant of the matrix is : 17.0
****************************************
using np.linalg.det() : 17.0
****************************************


Q2.Using **Gauss elimination method** to solve a system of equation by **backward substitution** method 

And verify the output **$A.\text{X} = \text{b}$** and check using **$\text{np.linalg.solve()}$**.

In [3]:
import numpy as np
def gauss_elmbk(a, b):
    m, n = a.shape               
    b = b.reshape(n,1)
    augmented_mat = np.hstack((a,b))
    np.set_printoptions(precision = 2, suppress = True)
    print('$ Original augmented matrix $')
    print(augmented_mat,'\n')
    print('# starting the elimination of matrix ') 
    for k in range(n):                       
        for j in range(k+1,n):                      
            q = float(augmented_mat[j][k]) / augmented_mat[k][k]       # lambda
            for m in range(k, n+1):    # Forward Elimination - Subtracting rows
                augmented_mat[j][m] -=  q * augmented_mat[k][m] 
    print('^^ this is the outstanding augmented matrix from Gauss elimation ^^')           
    print(augmented_mat)

    x = np.zeros(n)
    print('\n# From Backwards Substitution:')      
    x[n-1] = float(augmented_mat[n-1][n]) / augmented_mat[n-1][n-1]  
    for i in range (n-1,-1,-1):                 # Backwards Substitution 
        z = 0.0                                     
        for j in range(i+1,n):                     
            z = z  + float(augmented_mat[i][j])*x[j]   
        x[i] = float(augmented_mat[i][n] - z) / augmented_mat[i][i]
        print('x[%i]='%(i+1),x[i])
    print('the desired values of X are :',x,'\n')    
    
    # checking if A.X == b :
    B = np.dot(a,x.reshape(n,1))
    print("B = ",B.reshape(1,n)[0])
    if (B[i] == b[i]): print("Yes! It's a match,i.e., A.X == b")
    else : print("No! Its not a matching,i.e., A.X != b")
    return None

In [4]:
A = np. array([[ 1., 2.,-1., 1.],
               [-1., 1., 2.,-1.],
               [ 2.,-1., 2., 2.],
               [ 1., 1.,-1., 2.]])

b = np. array([ 6., 3., 14., 8.])

print('\nGaussian elimination  and back substitution:')
gauss_elmbk(A, b)
print('**************************************************************')
print(' direct read using numpy.linalg.solve():',np.linalg.solve(A, b)) 
print('**************************************************************')


Gaussian elimination  and back substitution:
$ Original augmented matrix $
[[ 1.  2. -1.  1.  6.]
 [-1.  1.  2. -1.  3.]
 [ 2. -1.  2.  2. 14.]
 [ 1.  1. -1.  2.  8.]] 

# starting the elimination of matrix 
^^ this is the outstanding augmented matrix from Gauss elimation ^^
[[ 1.    2.   -1.    1.    6.  ]
 [ 0.    3.    1.    0.    9.  ]
 [ 0.    0.    5.67  0.   17.  ]
 [ 0.    0.    0.    1.    4.  ]]

# From Backwards Substitution:
x[4]= 4.0
x[3]= 3.0
x[2]= 2.0
x[1]= 1.0
the desired values of X are : [1. 2. 3. 4.] 

B =  [ 6.  3. 14.  8.]
Yes! It's a match,i.e., A.X == b
**************************************************************
 direct read using numpy.linalg.solve(): [1. 2. 3. 4.]
**************************************************************


Q3.Using **Gauss elimination method with pivot and backward substitution method** to solve a system of equation 

And check the output **$A.\text{X} = \text{b}$** and verify using **$\text{np.linalg.solve()}$**.

In [5]:
import numpy as np
def gauss_pivot(a, b):
    m, n = a.shape               # verbose = output print precision
    b = b.reshape(n,1)
    augmented_mat = np.hstack((a,b))
    np.set_printoptions(precision = 2, suppress = True)
    print('$ Original augmented matrix $')
    print(augmented_mat,'\n')
    print('# starting the elimination of matrix ') 
    for k in range(n):       
        for i in range(k+1,n):        # Partial Pivoting 
            if abs(augmented_mat[i][k]) > abs(augmented_mat[k][k]):           
                augmented_mat[[k,i]] = augmented_mat[[i,k]]
                print('pivoting row [',i+1,'->',k+1,'] & row [',k,'->',i,']')
        for j in range(k+1,n):                      
            q = float(augmented_mat[j][k]) / augmented_mat[k][k]  # lambda
            for m in range(k, n+1): # Forward Elimination - Subtracting rows
                augmented_mat[j][m] -=  q * augmented_mat[k][m] 
                #print(augmented_mat,'\n')                
    print('^^ this is the outstanding augmented matrix from Gauss elimation ^^')           
    print(augmented_mat,'\n')
    x = np.zeros(n)
    print('# From Backwards Substitution:')      
    x[n-1] =float(augmented_mat[n-1][n]) / augmented_mat[n-1][n-1]  
    for i in range (n-1,-1,-1):         # Backwards Substitution         
        z = 0.0                                     
        for j in range(i+1,n):                     
            z = z  + float(augmented_mat[i][j])*x[j]   
        x[i] = float(augmented_mat[i][n] - z) / augmented_mat[i][i]
        print('x[%i]='%(i+1),x[i])
    print(' the desired values are :',x)    
    
    # checking if AX == b :
    B = np.dot(a,x.reshape(n,1))
    print("\nB = ",B.reshape(1,n)[0])
    if (B[i] == b[i]): print("Yes! It's a match,i.e., A.X == b")
    else : print("No! Its not a matching,i.e., A.X != b")
    return None

In [6]:
A = np. array([[ 1., 2.,-1., 1.],
               [-1., 1., 2.,-1.],
               [ 2.,-1., 2., 2.],
               [ 1., 1.,-1., 2.]])

b = np. array([ 6., 3., 14., 8.])

print('Gaussian elimination (with Pivotting) and back substitution: ')
gauss_pivot(A, b)
print('**************************************************************')
print(' direct read using numpy.linalg.solve():',np.linalg.solve(A, b)) 
print('**************************************************************')

Gaussian elimination (with Pivotting) and back substitution: 
$ Original augmented matrix $
[[ 1.  2. -1.  1.  6.]
 [-1.  1.  2. -1.  3.]
 [ 2. -1.  2.  2. 14.]
 [ 1.  1. -1.  2.  8.]] 

# starting the elimination of matrix 
pivoting row [ 3 -> 1 ] & row [ 0 -> 2 ]
pivoting row [ 3 -> 2 ] & row [ 1 -> 2 ]
^^ this is the outstanding augmented matrix from Gauss elimation ^^
[[ 2.  -1.   2.   2.  14. ]
 [ 0.   2.5 -2.   0.  -1. ]
 [ 0.   0.   3.4  0.  10.2]
 [ 0.   0.   0.   1.   4. ]] 

# From Backwards Substitution:
x[4]= 4.0
x[3]= 3.0
x[2]= 2.0
x[1]= 1.0
 the desired values are : [1. 2. 3. 4.]

B =  [ 6.  3. 14.  8.]
Yes! It's a match,i.e., A.X == b
**************************************************************
 direct read using numpy.linalg.solve(): [1. 2. 3. 4.]
**************************************************************


Q4.Using **Gauss elimination method** find the **inverse of matrix** and verify **$A.A^{-1} = \text{I}$** and check using **$\text{np.linalg.inv()}$**

In [19]:
import numpy as np
def gauss_elmbk_matrix_inverse(a):
    m, n = a.shape               
    b = np.identity(len(a))
    augmented_mat = np.hstack((a,b))
    np.set_printoptions(precision = 2, suppress = True)
    print('$ Original augmented matrix $')
    print(augmented_mat,'\n')
    print('# starting the elimination of matrix ') 
    for k in range(n+len(a)):                  
        for j in range(k+1,n):                      
            q = float(augmented_mat[j][k]) / augmented_mat[k][k]        # lambda
            for m in range(k, n+len(a)): # Forward Elimination - Subtracting rows 
                augmented_mat[j][m] -=  q * augmented_mat[k][m]  
    print('^^ this is the outstanding augmented matrix from Gauss elimation ^^')           
    print(augmented_mat,'\n')
    print('# From Backwards Substitution:')      
    for i in range(0, n):   # Backwards Substitution
        augmented_mat[i, :] = augmented_mat[i, :] / augmented_mat[i, i]
    print(augmented_mat)    
    print('\nINVERSE MATRIX IS:') 
    print(augmented_mat[:, n:])
    
    # check A.A⁻¹ == I
    print('\n# Product of of original and inverse matrix ')
    B = np.dot(a,augmented_mat[:, n:])
    print(B)
    if (B[i][j] == b[i][j]): print('Yes! Its an identity, i.e., A.A\u207B\u00B9 == I')
    else : print('No! Its not an identity, i.e., A.A\u207B\u00B9 != I')
    return None

In [20]:
A = np. array([[ 2.,  0.,  0.,  0.],
               [ 2.,  2.,  0.,  0.],
               [ 2.,  4.,  2.,  0.],
               [ 2.,  6.,  6.,  2.]])

print('\nGauss elimination method of matrix inverse: ')
gauss_elmbk_matrix_inverse(A)
print('******************************************************')
print('Using the function for direct read numpy.linalg.inv():')
print(np.linalg.inv(A))
print('******************************************************')


Gauss elimination method of matrix inverse: 
$ Original augmented matrix $
[[2. 0. 0. 0. 1. 0. 0. 0.]
 [2. 2. 0. 0. 0. 1. 0. 0.]
 [2. 4. 2. 0. 0. 0. 1. 0.]
 [2. 6. 6. 2. 0. 0. 0. 1.]] 

# starting the elimination of matrix 
^^ this is the outstanding augmented matrix from Gauss elimation ^^
[[ 2.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  2.  0.  0. -1.  1.  0.  0.]
 [ 0.  0.  2.  0.  1. -2.  1.  0.]
 [ 0.  0.  0.  2. -1.  3. -3.  1.]] 

# From Backwards Substitution:
[[ 1.   0.   0.   0.   0.5  0.   0.   0. ]
 [ 0.   1.   0.   0.  -0.5  0.5  0.   0. ]
 [ 0.   0.   1.   0.   0.5 -1.   0.5  0. ]
 [ 0.   0.   0.   1.  -0.5  1.5 -1.5  0.5]]

INVERSE MATRIX IS:
[[ 0.5  0.   0.   0. ]
 [-0.5  0.5  0.   0. ]
 [ 0.5 -1.   0.5  0. ]
 [-0.5  1.5 -1.5  0.5]]

# Product of of original and inverse matrix 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Yes! Its an identity, i.e., A.A⁻¹ == I
******************************************************
Using the function for direct read numpy.linal

Q5.Using **Gauss Jordan elimination** to solve a system of equation 

And verify the output **$A.\text{X} = \text{b}$** and check using **$\text{np.linalg.solve()}$**.

In [9]:
import numpy as np
def gauss_jordan(a, b):
    m, n = a.shape               
    b = b.reshape(n,1)
    augmented_mat = np.hstack((a,b))
    np.set_printoptions(precision = 2, suppress = True)
    print('$ Original augmented matrix $')
    print(augmented_mat,'\n')
    outer_loop = [[0, m - 1, 1], [m - 1, 0, -1]]
    for d in range(2):
        for i in range(outer_loop[d][0], outer_loop[d][1], outer_loop[d][2]):
            inner_loop = [[i + 1, m, 1], [i - 1, -1, -1]]
            for j in range(inner_loop[d][0], inner_loop[d][1], inner_loop[d][2]):
                k = (-1) * augmented_mat[j, i] / augmented_mat[i, i]
                temp_row = augmented_mat[i, :] * k
                augmented_mat[j, :] += temp_row
    for i in range(0, m):
        augmented_mat[i, :] = augmented_mat[i, :] / augmented_mat[i, i]
    print('# Normalizing the rows')
    print(augmented_mat)
    print('\nThe desired values of X are :',augmented_mat[:, n] ,'\n')    
    
    # checking if A.X == b :
    B = np.dot(a,augmented_mat[:, n].reshape(n,1))
    print("B = ",B.reshape(1,n)[0])
    if(B[i] == b[i]): print("Yes! It's a match,i.e., A.X == b")
    else : print("No! Its not a matching,i.e., A.X != b")
    return None

In [10]:
A = np.array([[10., -1.,   2.,  0.],
              [-1., 11.,  -1.,  3.],
              [ 2., -1.,  10., -1.],
              [ 0.,  3.,  -1.,  8.]])

b = np.array([6., 25., -11., 15.])

print(' Gauss Jordan elimination: ')
gauss_jordan(A, b)
print('*************************************************************')
print('direct read using numpy.linalg.solve():',np.linalg.solve(A, b))
print('*************************************************************')

 Gauss Jordan elimination: 
$ Original augmented matrix $
[[ 10.  -1.   2.   0.   6.]
 [ -1.  11.  -1.   3.  25.]
 [  2.  -1.  10.  -1. -11.]
 [  0.   3.  -1.   8.  15.]] 

# Normalizing the rows
[[ 1. -0. -0.  0.  1.]
 [ 0.  1. -0.  0.  2.]
 [ 0. -0.  1.  0. -1.]
 [ 0. -0.  0.  1.  1.]]

The desired values of X are : [ 1.  2. -1.  1.] 

B =  [  6.  25. -11.  15.]
Yes! It's a match,i.e., A.X == b
*************************************************************
direct read using numpy.linalg.solve(): [ 1.  2. -1.  1.]
*************************************************************


Q6. Using **Gauss Jordan elimination** find the **inverse of matrix** and verify **$A.A^{-1} = \text{I}$** and check using **$\text{np.linalg.inv()}$**

In [11]:
import numpy as np
def gauss_jordan_matrix_inverse(a):
    m, n = a.shape              
    b = np.identity(len(a))
    augmented_mat = np.hstack((a,b))
    np.set_printoptions(precision = 2, suppress = True)
    print('$ Original augmented matrix $')
    print(augmented_mat)
    outer_loop = [[0, m - 1, 1], [m - 1, 0, -1]]
    for d in range(2):
        for i in range(outer_loop[d][0], outer_loop[d][1], outer_loop[d][2]):
            inner_loop = [[i + 1, m, 1], [i - 1, -1, -1]]
            for j in range(inner_loop[d][0], inner_loop[d][1], inner_loop[d][2]):
                k = (-1) * augmented_mat[j, i] / augmented_mat[i, i]
                temp_row = augmented_mat[i, :] * k
                augmented_mat[j, :] += temp_row
    for i in range(0, m):
        augmented_mat[i, :] = augmented_mat[i, :] / augmented_mat[i, i]
    print('\n# Normalizing the rows')
    print(augmented_mat)   
    print('\nINVERSE MATRIX IS:') 
    print(augmented_mat[:, n:])
    
    # check A.A⁻¹ == I
    print('\n#product of of original and inverse matrix ')
    B = np.dot(a,augmented_mat[:, n:])
    print(B)
    if(B[i][j] == b[i][j]): print('Yes! Its an identity, i.e., A.A\u207B\u00B9 == I')
    else : print('No! Its not an identity , i.e., A.A\u207B\u00B9 != I')
    return None

In [12]:
A = np. array([[ 2.,  0.,  0.,  0.],
               [ 2.,  2.,  0.,  0.],
               [ 2.,  4.,  2.,  0.],
               [ 2.,  6.,  6.,  2.]])

print('Gauss Jordan method of matrix inverse: ')
gauss_jordan_matrix_inverse(A)
print('***************************************')
print(' direct read using numpy.linalg.inv(): ')
print(np.linalg.inv(A))
print('***************************************')

Gauss Jordan method of matrix inverse: 
$ Original augmented matrix $
[[2. 0. 0. 0. 1. 0. 0. 0.]
 [2. 2. 0. 0. 0. 1. 0. 0.]
 [2. 4. 2. 0. 0. 0. 1. 0.]
 [2. 6. 6. 2. 0. 0. 0. 1.]]

# Normalizing the rows
[[ 1.   0.   0.   0.   0.5  0.   0.   0. ]
 [ 0.   1.   0.   0.  -0.5  0.5  0.   0. ]
 [ 0.   0.   1.   0.   0.5 -1.   0.5  0. ]
 [ 0.   0.   0.   1.  -0.5  1.5 -1.5  0.5]]

INVERSE MATRIX IS:
[[ 0.5  0.   0.   0. ]
 [-0.5  0.5  0.   0. ]
 [ 0.5 -1.   0.5  0. ]
 [-0.5  1.5 -1.5  0.5]]

#product of of original and inverse matrix 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Yes! Its an identity, i.e., A.A⁻¹ == I
***************************************
 direct read using numpy.linalg.inv(): 
[[ 0.5  0.   0.   0. ]
 [-0.5  0.5  0.   0. ]
 [ 0.5 -1.   0.5 -0. ]
 [-0.5  1.5 -1.5  0.5]]
***************************************


Q7. Using **Jacobi iterative method** to solve a system of equation 

And verify the output **$A.\text{X} = \text{b}$** and check using **$\text{np.linalg.solve()}$**.

In [13]:
import numpy as np
def jacobi_iterative(a,b,limit = 100):
    m,n = a.shape
    print("Forming the system.:")             # prints the system
    np.set_printoptions(precision = 2, suppress = True)    
    for i in range(a.shape[0]):      # forming the eqn.
        row = ["{0:3g}*x{1}".format(a[i, j], j + 1) for j in range(a.shape[1])]
        print("{0} = {1:3g}".format(" + ".join(row), b[i]))    
    x = np.zeros_like(b)
    for it_count in range(limit+1):   
        x_new = np.zeros_like(x)
        for i in range(a.shape[0]):
            s1 = np.dot(a[i, :i], x[:i])
            s2 = np.dot(a[i, i + 1:], x[i + 1:])
            x_new[i] = (b[i] - s1 - s2) / a[i, i]
            if x_new[i] == x_new[i-1]:   # check for convergence
                break
        if np.allclose(x, x_new, atol=1e-10, rtol=0.):
            break
        x = x_new
        #print("Iteration {%i}: "%(it_count), x)
    print('Final output of x is :',x,'after {%i} count'%(it_count))
    
    # checking if A.X == b :
    x = x.reshape(n,1)
    B = np.round(np.dot(a,x).reshape(1,n)[0],2)
    print('\nB =',B)
    if(b[i] == B[i]): print('Yes! its a match,i.e., A.X == b ')
    else : print('No! its not a match,i.e., A.X != b ')
    return None

In [14]:
A = np.array([[10., -1.,   2.,  0.],
              [-1., 11.,  -1.,  3.],
              [ 2., -1.,  10., -1.],
              [ 0.,  3.,  -1.,  8.]])

b = np.array([6., 25., -11., 15.])

print('\nJacobi Iterative method : ')
jacobi_iterative(A,b)
print('**************************************************************')
print(' direct read using numpy.linalg.solve():',np.linalg.solve(A, b))
print('**************************************************************')


Jacobi Iterative method : 
Forming the system.:
 10*x1 +  -1*x2 +   2*x3 +   0*x4 =   6
 -1*x1 +  11*x2 +  -1*x3 +   3*x4 =  25
  2*x1 +  -1*x2 +  10*x3 +  -1*x4 = -11
  0*x1 +   3*x2 +  -1*x3 +   8*x4 =  15
Final output of x is : [ 1.  2. -1.  1.] after {28} count

B = [  6.  25. -11.  15.]
Yes! its a match,i.e., A.X == b 
**************************************************************
 direct read using numpy.linalg.solve(): [ 1.  2. -1.  1.]
**************************************************************


Q8.Using **Gauss Seidel iterative method** to solve a system of equation 
    
And verify the output **$A.\text{X} = \text{b}$** and check using **$\text{np.linalg.solve()}$**.

In [15]:
import numpy as np
def gauss_seidel(a,b,verbose=0,limit=1000):
    m,n = a.shape
    print("System of equations:")
    np.set_printoptions(precision=2, suppress=True)
    for i in range(A.shape[0]):      # forming the eqn.
        row = ["{0:3g}*x{1}".format(A[i, j], j + 1) for j in range(A.shape[1])]
        print("{0} = {1:3g}".format(" + ".join(row), b[i]))    
    x = np.zeros_like(b)
    for it_count in range(1, limit):
        x_new = np.zeros_like(x)
        #print("Iteration {%i}: "%(it_count), x)
        for i in range(A.shape[0]):
            s1 = np.dot(A[i, :i], x_new[:i])
            s2 = np.dot(A[i, i + 1 :], x[i + 1 :])
            x_new[i] = (b[i] - s1 - s2) / A[i, i]
        if np.allclose(x, x_new, rtol=1e-8):    # check for convergence
            break
        x = x_new
    print("\nFinal output X is :",x,"after {%i} counts"%(it_count))
    
    # check if A.X == b:
    B = np.dot(a,x.reshape(n,1))
    print('\nB = ',B.reshape(1,n)[0])
    if(b[i] == B[i]):
        print('Yes! its a match,i.e., A.X == b ')
    else :
        print('No! its not a match,i.e., A.X != b ')
    return None

In [16]:
A = np.array([[10., -1.,   2.,  0.],
              [-1., 11.,  -1.,  3.],
              [ 2., -1.,  10., -1.],
              [ 0.,  3.,  -1.,  8.]])

b = np.array([6., 25., -11., 15.])

print('\nGauss Seidel iterative method : ')
gauss_seidel(A,b)
print('**************************************************************')
print(' direct read using numpy.linalg.solve():',np.linalg.solve(A, b)) 
print('**************************************************************')


Gauss Seidel iterative method : 
System of equations:
 10*x1 +  -1*x2 +   2*x3 +   0*x4 =   6
 -1*x1 +  11*x2 +  -1*x3 +   3*x4 =  25
  2*x1 +  -1*x2 +  10*x3 +  -1*x4 = -11
  0*x1 +   3*x2 +  -1*x3 +   8*x4 =  15

Final output X is : [ 1.  2. -1.  1.] after {10} counts

B =  [  6.  25. -11.  15.]
Yes! its a match,i.e., A.X == b 
**************************************************************
 direct read using numpy.linalg.solve(): [ 1.  2. -1.  1.]
**************************************************************


Q9. Find the largest eigenvalue of matrix by **Power method** 

And verify **$A.\text{X}=\lambda.\text{X}$** and check the solution using **$\text{np.linalg.eig()}$**

In [17]:
import numpy as np
def largest_eigenvalue_power_method(a):
    n= a.shape[0]
    np.set_printoptions(precision=2, suppress=True)
    def normalize(x):
        fac = abs(x).max()
        x_n = x / x.max()
        return fac, x_n
    x = np.ones(len(a))
    for i in range(2*len(a)**2):
        x = np.dot(a, x)
        lambda_1,x = normalize(x)
    print('Largest Eigenvalue is :',np.round(lambda_1),2)
    print('X =',x)
    
    # check if A.X == λ.X
    AX=np.round(np.dot(a,x),2)
    lx=np.round(np.dot(lambda_1,x),2)
    print('A.X =',AX,'\n\u03BB.X =',lx)
    f=0
    for i,j in zip(AX,lx):
        if( i == j): f += 1
        else : f += 0
    if (f > 0): print('Yes! Its a match,i.e., A.X == \u03BB.X')
    else : print('No! Its not a match,i.e., A.X != \u03BB.X')
    return None

In [18]:
A = np.array([[ 1., 5.,-3., 9.],
              [ 5., 0., 2., 1.],
              [-3., 2., 8., 4.],
              [ 9.,-1., 4., 6.]])

print("Power method for largest Eigenvalue:")
largest_eigenvalue_power_method(A)

print('***************************************************************************************')
x = np.linalg.eig(A)
print(' direct read using np.linalg.eig(A):', x[0]) 
print('***************************************************************************************')

Power method for largest Eigenvalue:
Largest Eigenvalue is : 14.0 2
X = [0.75 0.4  0.42 1.  ]
A.X = [10.46  5.58  5.96 14.02] 
λ.X = [10.46  5.58  5.96 14.02]
Yes! Its a match,i.e., A.X == λ.X
***************************************************************************************
 direct read using np.linalg.eig(A): [-9.41 14.02  9.07  1.32]
***************************************************************************************
