Q1.Using **Gauss elimination method** to form a upper triangulation of matrix step-wise .
       
And then find the **determinant** by multiplying its diagonal and check using np.linalg.det()

In [58]:
import numpy as np
def gauss(a):
    m, n = a.shape               
    augment_mat = a
    np.set_printoptions(precision=2, suppress=True)

    print('$ Original augment matrix $')
    print(augment_mat,'\n')
    print('# starting the elimination of matrix ') 
    
    for k in range(n):                        
        for j in range(k+1,n):                      
            q = float(augment_mat[j][k]) / augment_mat[k][k]  # lambda
            for m in range(k, n): 
                augment_mat[j][m] -=  q * augment_mat[k][m]
                 
    print('^^ this is the outstanding upper triangulated matrix from Gauss elimation ^^')           
    print(augment_mat,'\n')
    M=1        
    for i in range(n):
        M*=augment_mat[i][i]
    print('Determinant of the augment matrix is :',M)
    return None

In [61]:
# Inputs of 4x4 Matrix
A = np. array([[ 1., 2.,-1., 1.],
               [-1., 1., 2.,-1.],
               [ 2.,-1., 2., 2.],
               [ 1., 1.,-1., 2.]])

print('\nGaussian elimination:  ')
gauss(A)
print('\n*********************************************************************************')
print('using np.linalg.det() :',np.linalg.det(A))
print('\n*********************************************************************************')


Gaussian elimination:  
$ Original augment matrix $
[[ 1.  2. -1.  1.]
 [-1.  1.  2. -1.]
 [ 2. -1.  2.  2.]
 [ 1.  1. -1.  2.]] 

# starting the elimination of matrix 
^^ this is the outstanding upper triangulated matrix from Gauss elimation ^^
[[ 1.    2.   -1.    1.  ]
 [ 0.    3.    1.    0.  ]
 [ 0.    0.    5.67  0.  ]
 [ 0.    0.    0.    1.  ]] 

Determinant of the augment matrix is : 17.0

*********************************************************************************
using np.linalg.det() : 17.0

*********************************************************************************


In [62]:
# Inputs of 5x5 Matrix
A = np. array([[11.,  3.,  0.,  1.,  2.],
               [ 0.,  4.,  2.,  0.,  1.],
               [ 3.,  2.,  7.,  1.,  0.],
               [ 4.,  0.,  4., 10.,  1.],
               [ 2.,  5.,  1.,  2., 13.]])

print('\nGaussian elimination:  ')
gauss(A)
print('\n*********************************************************************************')
print('using np.linalg.det() :',np.linalg.det(A))
print('\n*********************************************************************************')


Gaussian elimination:  
$ Original augment matrix $
[[11.  3.  0.  1.  2.]
 [ 0.  4.  2.  0.  1.]
 [ 3.  2.  7.  1.  0.]
 [ 4.  0.  4. 10.  1.]
 [ 2.  5.  1.  2. 13.]] 

# starting the elimination of matrix 
^^ this is the outstanding upper triangulated matrix from Gauss elimation ^^
[[11.    3.    0.    1.    2.  ]
 [ 0.    4.    2.    0.    1.  ]
 [ 0.    0.    6.41  0.73 -0.84]
 [ 0.    0.    0.    9.12  1.14]
 [ 0.    0.    0.    0.   11.12]] 

Determinant of the augment matrix is : 28592.0

*********************************************************************************
using np.linalg.det() : 28591.999999999975

*********************************************************************************


Q2.Using **Gauss elimination method** to solve a liner equation by **backward substitution** method and check using np.linalg.solve()

In [63]:
import numpy as np
def gauss_elmbk(a, b, verbose=0):
    m, n = a.shape               
    b=b.reshape(n,1)
    augmented_mat = np.hstack((a,b))
    np.set_printoptions(precision=2, suppress=True)
   
    print('$ Original augmented matrix $')
    print(augmented_mat,'\n')
    print('# starting the elimination of matrix ') 
    
    for k in range(n):                       
        for j in range(k+1,n):                      
            q = float(augmented_mat[j][k]) / augmented_mat[k][k]  # lambda
            for m in range(k, n+1): 
                augmented_mat[j][m] -=  q * augmented_mat[k][m] # Forward Elimination - Subtracting rows
                
    print('^^ this is the outstanding augmented matrix from Gauss elimation ^^')           
    print(augmented_mat,'\n')
        
    # Backwards Substitution       
    x = np.zeros(n)
    print('\n# From Backwards Substitution:')      
    x[n-1] =float(augmented_mat[n-1][n])/augmented_mat[n-1][n-1]  
    for i in range (n-1,-1,-1):                 
        z = 0.0                                     
        for j in range(i+1,n):                     
            z = z  + float(augmented_mat[i][j])*x[j]   
        x[i] = float(augmented_mat[i][n] - z) / augmented_mat[i][i]
        print('x[%i]='%(i+1),float(augmented_mat[i][n] - z) ,'/',augmented_mat[i][i],'=',x[i])
    print('\n the desired values are :',x)    
    return None

In [65]:
# Inputs of 4x4 Matrix
A = np. array([[ 1., 2.,-1., 1.],
               [-1., 1., 2.,-1.],
               [ 2.,-1., 2., 2.],
               [ 1., 1.,-1., 2.]])

b = np. array([ 6., 3., 14., 8.])

print('\nGaussian elimination  and back substitution:')
gauss_elmbk(A, b, i)
print('\n*********************************************************************************')
print('\nUsing the function for direct read numpy.linalg.solve():',np.linalg.solve(A, b)) 
print('\n*********************************************************************************')


Gaussian elimination  and back substitution:
$ Original augmented matrix $
[[ 1.  2. -1.  1.  6.]
 [-1.  1.  2. -1.  3.]
 [ 2. -1.  2.  2. 14.]
 [ 1.  1. -1.  2.  8.]] 

# starting the elimination of matrix 
^^ this is the outstanding augmented matrix from Gauss elimation ^^
[[ 1.    2.   -1.    1.    6.  ]
 [ 0.    3.    1.    0.    9.  ]
 [ 0.    0.    5.67  0.   17.  ]
 [ 0.    0.    0.    1.    4.  ]] 


# From Backwards Substitution:
x[4]= 4.0 / 1.0 = 4.0
x[3]= 17.0 / 5.666666666666667 = 3.0
x[2]= 6.0 / 3.0 = 2.0
x[1]= 1.0 / 1.0 = 1.0

 the desired values are : [1. 2. 3. 4.]

*********************************************************************************

Using the function for direct read numpy.linalg.solve(): [1. 2. 3. 4.]

*********************************************************************************


In [66]:
# Inputs of 5x5 Matrix
A = np. array([[11.,  3.,  0.,  1.,  2.],
               [ 0.,  4.,  2.,  0.,  1.],
               [ 3.,  2.,  7.,  1.,  0.],
               [ 4.,  0.,  4., 10.,  1.],
               [ 2.,  5.,  1.,  2., 13.]])

b = np. array([51., 15.,  15., 20., 92.])

print('\nGaussian elimination  and back substitution:')
gauss_elmbk(A, b, i)
print('\n*********************************************************************************')
print('\nUsing the function for direct read numpy.linalg.solve():',np.linalg.solve(A, b)) 
print('\n*********************************************************************************') 


Gaussian elimination  and back substitution:
$ Original augmented matrix $
[[11.  3.  0.  1.  2. 51.]
 [ 0.  4.  2.  0.  1. 15.]
 [ 3.  2.  7.  1.  0. 15.]
 [ 4.  0.  4. 10.  1. 20.]
 [ 2.  5.  1.  2. 13. 92.]] 

# starting the elimination of matrix 
^^ this is the outstanding augmented matrix from Gauss elimation ^^
[[11.    3.    0.    1.    2.   51.  ]
 [ 0.    4.    2.    0.    1.   15.  ]
 [ 0.    0.    6.41  0.73 -0.84 -3.34]
 [ 0.    0.    0.    9.12  1.14  7.91]
 [ 0.    0.    0.    0.   11.12 63.68]] 


# From Backwards Substitution:
x[5]= 63.68429237947122 / 11.116640746500778 = 5.7287353105763845
x[4]= 1.373571737568808 / 9.120567375886525 = 0.1506015668718522
x[3]= 1.3669080988960678 / 6.409090909090909 = 0.21327644096250703
x[2]= 8.844711807498602 / 4.0 = 2.2111779518746504
x[1]= 32.758393956351426 / 11.0 = 2.978035814213766

 the desired values are : [2.98 2.21 0.21 0.15 5.73]

*********************************************************************************

Using the f

Q3.Using **Gauss elimination method with pivot and backward substitution method** to solve a liner equation and check using np.linalg.solve()

In [65]:
import numpy as np
def gauss_pivot(a, b):
    m, n = a.shape               # verbose = output print precision
    b=b.reshape(n,1)
    augmented_mat = np.hstack((a,b))
    np.set_printoptions(precision=2, suppress=True)
    
    print('$ Original augmented matrix $')
    print(augmented_mat,'\n')
    print('# starting the elimination of matrix by choosing a pivot eqn. ') 
    
    for k in range(n):       
        # Partial Pivoting 
        for i in range(k+1,n):      # 0=n              
            if abs(augmented_mat[i][k]) > abs(augmented_mat[k][k]):           
                augmented_mat[[k,i]]=augmented_mat[[i,k]]
                print(i,k)
                print(augmented_mat,'\n')
            
        for j in range(k+1,n):                      
            q = float(augmented_mat[j][k]) / augmented_mat[k][k]  # lambda
            for m in range(k, n+1): 
                augmented_mat[j][m] -=  q * augmented_mat[k][m] # Forward Elimination - Subtracting rows
                                
    print('^^ this is the outstanding augmented matrix from Gauss elimation ^^')           
    print(augmented_mat,'\n')
        
    # Backwards Substitution
    x = np.zeros(n)
    print('\n# From Backwards Substitution:')      
    x[n-1] =float(augmented_mat[n-1][n])/augmented_mat[n-1][n-1]  
    for i in range (n-1,-1,-1):                 
        z = 0.0                                     
        for j in range(i+1,n):                     
            z = z  + float(augmented_mat[i][j])*x[j]   
        x[i] = float(augmented_mat[i][n] - z) / augmented_mat[i][i]
        print('x[%i]='%(i+1),float(augmented_mat[i][n] - z) ,'/',augmented_mat[i][i],'=',x[i])
    print('\n the desired values are :',x)    
    return None

In [66]:
# Inputs of 4x4 Matrix
A = np. array([[ 1., 2.,-1., 1.],
               [-1., 1., 2.,-1.],
               [ 2.,-1., 2., 2.],
               [ 1., 1.,-1., 2.]])

b = np. array([ 6., 3., 14., 8.])

print('\nGaussian elimination (with Pivotting) and back substitution: ')
gauss_pivot(A, b)
print('\n*********************************************************************************')
print('\nUsing the function for direct read numpy.linalg.solve():',np.linalg.solve(A, b)) 
print('\n*********************************************************************************')


Gaussian elimination (with Pivotting) and back substitution: 
$ Original augmented matrix $
[[ 1.  2. -1.  1.  6.]
 [-1.  1.  2. -1.  3.]
 [ 2. -1.  2.  2. 14.]
 [ 1.  1. -1.  2.  8.]] 

# starting the elimination of matrix by choosing a pivot eqn. 
2 0
[[ 2. -1.  2.  2. 14.]
 [-1.  1.  2. -1.  3.]
 [ 1.  2. -1.  1.  6.]
 [ 1.  1. -1.  2.  8.]] 

2 1
[[ 2.  -1.   2.   2.  14. ]
 [ 0.   2.5 -2.   0.  -1. ]
 [ 0.   0.5  3.   0.  10. ]
 [ 0.   1.5 -2.   1.   1. ]] 

^^ this is the outstanding augmented matrix from Gauss elimation ^^
[[ 2.  -1.   2.   2.  14. ]
 [ 0.   2.5 -2.   0.  -1. ]
 [ 0.   0.   3.4  0.  10.2]
 [ 0.   0.   0.   1.   4. ]] 


# From Backwards Substitution:
x[4]= 4.0 / 1.0 = 4.0
x[3]= 10.2 / 3.4 = 3.0
x[2]= 5.0 / 2.5 = 2.0
x[1]= 2.0 / 2.0 = 1.0

 the desired values are : [1. 2. 3. 4.]

*********************************************************************************

Using the function for direct read numpy.linalg.solve(): [1. 2. 3. 4.]

******************************

In [67]:
# Inputs of 5x5 Matrix
A = np. array([[11.,  3.,  0.,  1.,  2.],
               [ 0.,  4.,  2.,  0.,  1.],
               [ 3.,  2.,  7.,  1.,  0.],
               [ 4.,  0.,  4., 10.,  1.],
               [ 2.,  5.,  1.,  2., 13.]])

b = np. array([51., 15.,  15., 20., 92.])

print('\nGaussian elimination (with Pivotting) and back substitution: ')
gauss_pivot(A, b)
print('\n*********************************************************************************')
print('\nUsing the function for direct read numpy.linalg.solve():',np.linalg.solve(A, b)) 
print('\n*********************************************************************************')


Gaussian elimination (with Pivotting) and back substitution: 
$ Original augmented matrix $
[[11.  3.  0.  1.  2. 51.]
 [ 0.  4.  2.  0.  1. 15.]
 [ 3.  2.  7.  1.  0. 15.]
 [ 4.  0.  4. 10.  1. 20.]
 [ 2.  5.  1.  2. 13. 92.]] 

# starting the elimination of matrix by choosing a pivot eqn. 
4 1
[[11.    3.    0.    1.    2.   51.  ]
 [ 0.    4.45  1.    1.82 12.64 82.73]
 [ 0.    1.18  7.    0.73 -0.55  1.09]
 [ 0.   -1.09  4.    9.64  0.27  1.45]
 [ 0.    4.    2.    0.    1.   15.  ]] 

^^ this is the outstanding augmented matrix from Gauss elimation ^^
[[ 11.     3.     0.     1.     2.    51.  ]
 [  0.     4.45   1.     1.82  12.64  82.73]
 [  0.     0.     6.73   0.24  -3.9  -20.86]
 [  0.     0.     0.     9.93   5.82  34.86]
 [  0.     0.     0.     0.    -8.73 -50.  ]] 


# From Backwards Substitution:
x[5]= -49.99877899877898 / -8.727716727716727 = 5.728735310576384
x[4]= 1.4950628274914806 / 9.927272727272728 = 0.15060156687185244
x[3]= 1.4363515411760623 / 6.73469387755102

Q4.Find the **matrix inverse using Gauss elimination method** and check if the product of original and inverse matrix is identity or not and also using np.linalg.inv()

In [9]:
import numpy as np
def gauss_elmbk_matrix_inverse(a):
    m, n = a.shape               # verbose = output print precision
    b=np.identity(len(a))
    augmented_mat = np.hstack((a,b))
    np.set_printoptions(precision=2, suppress=True)
    print('$ Original augmented matrix $')
    print(augmented_mat,'\n')
    print('# starting the elimination of matrix ') 
    
    for k in range(n+len(a)):                  
        # Forward Elimination - Subtracting rows     
        for j in range(k+1,n):                      
            q = float(augmented_mat[j][k]) / augmented_mat[k][k]  # lambda
            for m in range(k, n+len(a)): 
                augmented_mat[j][m] -=  q * augmented_mat[k][m]  
    print('^^ this is the outstanding augmented matrix from Gauss elimation ^^')           
    print(augmented_mat,'\n')
    
    # Backwards Substitution
    print('\n# From Backwards Substitution:')      
    for i in range(0, n):
        augmented_mat[i, :] = augmented_mat[i, :] / augmented_mat[i, i]
    print(augmented_mat)    
    print('\nINVERSE MATRIX IS:') 
    print(augmented_mat[:, n:])
    
    # check for inverse - by product of original and inverse matrix
    print('\n#product of of original and inverse matrix ')
    print(np.dot(a,augmented_mat[:, n:]))
    return None

In [10]:
# Input of 4x4 Matrix
A = np. array([[ 2.,  0.,  0.,  0.],
               [ 2.,  2.,  0.,  0.],
               [ 2.,  4.,  2.,  0.],
               [ 2.,  6.,  6.,  2.]])

print('\nGauss elimination method of matrix inverse: ')
gauss_elmbk_matrix_inverse(A)
print('\n*********************************************************************************************')
print('\nUsing the function for direct read numpy.linalg.inv():')
print(np.linalg.inv(A))
print('\n*********************************************************************************************')


Gauss elimination method of matrix inverse: 
$ Original augmented matrix $
[[2. 0. 0. 0. 1. 0. 0. 0.]
 [2. 2. 0. 0. 0. 1. 0. 0.]
 [2. 4. 2. 0. 0. 0. 1. 0.]
 [2. 6. 6. 2. 0. 0. 0. 1.]] 

# starting the elimination of matrix 
^^ this is the outstanding augmented matrix from Gauss elimation ^^
[[ 2.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  2.  0.  0. -1.  1.  0.  0.]
 [ 0.  0.  2.  0.  1. -2.  1.  0.]
 [ 0.  0.  0.  2. -1.  3. -3.  1.]] 


# From Backwards Substitution:
[[ 1.   0.   0.   0.   0.5  0.   0.   0. ]
 [ 0.   1.   0.   0.  -0.5  0.5  0.   0. ]
 [ 0.   0.   1.   0.   0.5 -1.   0.5  0. ]
 [ 0.   0.   0.   1.  -0.5  1.5 -1.5  0.5]]

INVERSE MATRIX IS:
[[ 0.5  0.   0.   0. ]
 [-0.5  0.5  0.   0. ]
 [ 0.5 -1.   0.5  0. ]
 [-0.5  1.5 -1.5  0.5]]

#product of of original and inverse matrix 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

*********************************************************************************************

Using the function for direct read numpy.lin

In [8]:
# Input of 5x5 Matrix
A = np. array([[ 2.,  0.,  0.,  0.,  0.],
               [ 2.,  2.,  0.,  0.,  0.],
               [ 2.,  4.,  2.,  0.,  0.],
               [ 2.,  6.,  6.,  2.,  0.],
               [ 2.,  8., 12.,  8.,  2.]])

print('\nGauss elimination method of matrix inverse: ')
gauss_elmbk_matrix_inverse(A)
print('\n*********************************************************************************************')
print('\nUsing the function for direct read numpy.linalg.inv():')
print(np.linalg.inv(A))
print('\n*********************************************************************************************')


Gauss elimination method of matrix inverse: 
$ Original augmented matrix $
[[ 2.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 2.  2.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 2.  4.  2.  0.  0.  0.  0.  1.  0.  0.]
 [ 2.  6.  6.  2.  0.  0.  0.  0.  1.  0.]
 [ 2.  8. 12.  8.  2.  0.  0.  0.  0.  1.]] 

# starting the elimination of matrix 
^^ this is the outstanding augmented matrix from Gauss elimation ^^
[[ 2.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  2.  0.  0.  0. -1.  1.  0.  0.  0.]
 [ 0.  0.  2.  0.  0.  1. -2.  1.  0.  0.]
 [ 0.  0.  0.  2.  0. -1.  3. -3.  1.  0.]
 [ 0.  0.  0.  0.  2.  1. -4.  6. -4.  1.]] 


# From Backwards Substitution:
[[ 1.   0.   0.   0.   0.   0.5  0.   0.   0.   0. ]
 [ 0.   1.   0.   0.   0.  -0.5  0.5  0.   0.   0. ]
 [ 0.   0.   1.   0.   0.   0.5 -1.   0.5  0.   0. ]
 [ 0.   0.   0.   1.   0.  -0.5  1.5 -1.5  0.5  0. ]
 [ 0.   0.   0.   0.   1.   0.5 -2.   3.  -2.   0.5]]

INVERSE MATRIX IS:
[[ 0.5  0.   0.   0.   0. ]
 [-0.5  0.5  0.   0.   0. ]
 [ 0.5 -

Q5.Using **Gauss Jordan elimination** to solve a liner equation and check using np.linalg.solve()

In [53]:
import numpy as np
def gauss_jordan(a, b):
    m, n = a.shape               
    b=b.reshape(n,1)
    augmented_mat = np.hstack((a,b))
    np.set_printoptions(precision=2, suppress=True)
    
    print('$ Original augmented matrix $')
    print(augmented_mat,'\n')
    outer_loop = [[0, m - 1, 1], [m - 1, 0, -1]]
    
    for d in range(2):
        for i in range(outer_loop[d][0], outer_loop[d][1], outer_loop[d][2]):
            inner_loop = [[i + 1, m, 1], [i - 1, -1, -1]]
            
            for j in range(inner_loop[d][0], inner_loop[d][1], inner_loop[d][2]):
                k = (-1) * augmented_mat[j, i] / augmented_mat[i, i]
                temp_row = augmented_mat[i, :] * k
                
                augmented_mat[j, :] += temp_row
                    
    for i in range(0, m):
        augmented_mat[i, :] = augmented_mat[i, :] / augmented_mat[i, i]

    print('# Normalizing the rows')
    print(augmented_mat)
    print('\nNow after taking the last column we get,\nthe desired values are :',augmented_mat[:, n] )    
    return None

In [54]:
# Inputs of 5x5 Matrix
A = np. array([[11.,  3.,  0.,  1.,  2.],
               [ 0.,  4.,  2.,  0.,  1.],
               [ 3.,  2.,  7.,  1.,  0.],
               [ 4.,  0.,  4., 10.,  1.],
               [ 2.,  5.,  1.,  2., 13.]])

b = np. array([51., 15.,  15., 20., 92.])

print('\n Gauss Jordan elimination: ')
gauss_jordan(A, b)
print('\n*********************************************************************************************')
print('\nUsing the function for direct read numpy.linalg.solve():',np.linalg.solve(A, b))
print('\n*********************************************************************************************')


 Gauss Jordan elimination: 
$ Original augmented matrix $
[[11.  3.  0.  1.  2. 51.]
 [ 0.  4.  2.  0.  1. 15.]
 [ 3.  2.  7.  1.  0. 15.]
 [ 4.  0.  4. 10.  1. 20.]
 [ 2.  5.  1.  2. 13. 92.]] 

# Normalizing the rows
[[ 1.    0.    0.    0.    0.    2.98]
 [ 0.    1.    0.    0.   -0.    2.21]
 [ 0.    0.    1.    0.    0.    0.21]
 [ 0.    0.    0.    1.    0.    0.15]
 [ 0.    0.    0.    0.    1.    5.73]]

Now after taking the last column we get,
the desired values are : [2.98 2.21 0.21 0.15 5.73]

*********************************************************************************************

Using the function for direct read numpy.linalg.solve(): [2.98 2.21 0.21 0.15 5.73]

*********************************************************************************************


In [67]:
# Inputs of 4x4 matrix
A = np.array([[10., -1.,   2.,  0.],
              [-1., 11.,  -1.,  3.],
              [ 2., -1.,  10., -1.],
              [ 0.,  3.,  -1.,  8.]])

b = np.array([6., 25., -11., 15.])

print('\n Gauss Jordan elimination: ')
gauss_jordan(A, b)
print('\n*********************************************************************************************')
print('\nUsing the function for direct read numpy.linalg.solve():',np.linalg.solve(A, b))
print('\n*********************************************************************************************')


 Gauss Jordan elimination: 
$ Original augmented matrix $
[[ 10.  -1.   2.   0.   6.]
 [ -1.  11.  -1.   3.  25.]
 [  2.  -1.  10.  -1. -11.]
 [  0.   3.  -1.   8.  15.]] 

# Normalizing the rows
[[ 1. -0. -0.  0.  1.]
 [ 0.  1. -0.  0.  2.]
 [ 0. -0.  1.  0. -1.]
 [ 0. -0.  0.  1.  1.]]

Now after taking the last column we get,
the desired values are : [ 1.  2. -1.  1.]

*********************************************************************************************

Using the function for direct read numpy.linalg.solve(): [ 1.  2. -1.  1.]

*********************************************************************************************


Q6.Find the **inverse of a matrix** by **Gauss Jordan elimination**  and check if the product of original and inverse matrix is identity or not and also using np.linalg.inv() and also check using np.linalg.inv()

In [11]:
import numpy as np
def gauss_jordan_matrix_inverse(a):
    m, n = a.shape              
    b=np.identity(len(a))
    augmented_mat = np.hstack((a,b))
    np.set_printoptions(precision=2, suppress=True)
    print('$ Original augmented matrix $')
    print(augmented_mat)
    outer_loop = [[0, m - 1, 1], [m - 1, 0, -1]]
    for d in range(2):
        for i in range(outer_loop[d][0], outer_loop[d][1], outer_loop[d][2]):
            inner_loop = [[i + 1, m, 1], [i - 1, -1, -1]]
            for j in range(inner_loop[d][0], inner_loop[d][1], inner_loop[d][2]):
                k = (-1) * augmented_mat[j, i] / augmented_mat[i, i]
                temp_row = augmented_mat[i, :] * k
                augmented_mat[j, :] += temp_row
                    
    for i in range(0, m):
        augmented_mat[i, :] = augmented_mat[i, :] / augmented_mat[i, i]
    print('\n# Normalizing the rows')
    print(augmented_mat)   
    print('\nINVERSE MATRIX IS:') 
    print(augmented_mat[:, n:])
    
    # check for inverse - by product of original and inverse matrix
    print('\n#product of of original and inverse matrix ')
    print(np.dot(a,augmented_mat[:, n:]))
    return None

In [13]:
# Inputs 4x4 matrix
A = np. array([[ 2.,  0.,  0.,  0.],
               [ 2.,  2.,  0.,  0.],
               [ 2.,  4.,  2.,  0.],
               [ 2.,  6.,  6.,  2.]])

print('\nGauss Jordan method of matrix inverse: ')
gauss_jordan_matrix_inverse(A)
print('\n*********************************************************************************************')
print('\nUsing the function for direct read numpy.linalg.inv():')
print(np.linalg.inv(A))
print('\n*********************************************************************************************')


Gauss Jordan method of matrix inverse: 
$ Original augmented matrix $
[[2. 0. 0. 0. 1. 0. 0. 0.]
 [2. 2. 0. 0. 0. 1. 0. 0.]
 [2. 4. 2. 0. 0. 0. 1. 0.]
 [2. 6. 6. 2. 0. 0. 0. 1.]]

# Normalizing the rows
[[ 1.   0.   0.   0.   0.5  0.   0.   0. ]
 [ 0.   1.   0.   0.  -0.5  0.5  0.   0. ]
 [ 0.   0.   1.   0.   0.5 -1.   0.5  0. ]
 [ 0.   0.   0.   1.  -0.5  1.5 -1.5  0.5]]

INVERSE MATRIX IS:
[[ 0.5  0.   0.   0. ]
 [-0.5  0.5  0.   0. ]
 [ 0.5 -1.   0.5  0. ]
 [-0.5  1.5 -1.5  0.5]]

#product of of original and inverse matrix 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

*********************************************************************************************

Using the function for direct read numpy.linalg.inv():
[[ 0.5  0.   0.   0. ]
 [-0.5  0.5  0.   0. ]
 [ 0.5 -1.   0.5 -0. ]
 [-0.5  1.5 -1.5  0.5]]

*********************************************************************************************


In [14]:
# Input of 5x5 Matrix
A = np. array([[ 2.,  0.,  0.,  0.,  0.],
               [ 2.,  2.,  0.,  0.,  0.],
               [ 2.,  4.,  2.,  0.,  0.],
               [ 2.,  6.,  6.,  2.,  0.],
               [ 2.,  8., 12.,  8.,  2.]])

print('\nGauss Jordan method of matrix inverse: ')
gauss_jordan_matrix_inverse(A)
print('\n*********************************************************************************************')
print('\nUsing the function for direct read numpy.linalg.inv():')
print(np.linalg.inv(A))
print('\n*********************************************************************************************')


Gauss Jordan method of matrix inverse: 
$ Original augmented matrix $
[[ 2.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 2.  2.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 2.  4.  2.  0.  0.  0.  0.  1.  0.  0.]
 [ 2.  6.  6.  2.  0.  0.  0.  0.  1.  0.]
 [ 2.  8. 12.  8.  2.  0.  0.  0.  0.  1.]]

# Normalizing the rows
[[ 1.   0.   0.   0.   0.   0.5  0.   0.   0.   0. ]
 [ 0.   1.   0.   0.   0.  -0.5  0.5  0.   0.   0. ]
 [ 0.   0.   1.   0.   0.   0.5 -1.   0.5  0.   0. ]
 [ 0.   0.   0.   1.   0.  -0.5  1.5 -1.5  0.5  0. ]
 [ 0.   0.   0.   0.   1.   0.5 -2.   3.  -2.   0.5]]

INVERSE MATRIX IS:
[[ 0.5  0.   0.   0.   0. ]
 [-0.5  0.5  0.   0.   0. ]
 [ 0.5 -1.   0.5  0.   0. ]
 [-0.5  1.5 -1.5  0.5  0. ]
 [ 0.5 -2.   3.  -2.   0.5]]

#product of of original and inverse matrix 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

*********************************************************************************************

Using the function for direct 

---------------------------------------------------------------------------------------------------------------------------

Q4. Solve a system of equation by **Jacobi iterative method**.
   
Verify if the equations are satisfied by your solutions using np.linalg.solve()

In [26]:
import numpy as np
def jacobi_iterative(A,b,limit = 100):
    print("Forming the eqn.:")             # prints the system
    np.set_printoptions(precision=2, suppress=True)    
    for i in range(A.shape[0]):            # forming the enq.
        row = ["{}*x{}".format(A[i, j], j + 1) for j in range(A.shape[1])]
        print(f'{" + ".join(row)} = {b[i]}')
    print()
    x = np.zeros_like(b)
    for it_count in range(limit+1):
        if it_count != 0:
            print("Iteration {0}: {1}".format(it_count, x))
        x_new = np.zeros_like(x)
        for i in range(A.shape[0]):
            s1 = np.dot(A[i, :i], x[:i])
            s2 = np.dot(A[i, i + 1:], x[i + 1:])
            x_new[i] = (b[i] - s1 - s2) / A[i, i]
            if x_new[i] == x_new[i-1]:   # check for convergence
                break
        if np.allclose(x, x_new, atol=1e-10, rtol=0.):
            break
        x = x_new
    print('solution from Jacobi iterative method :',x)
    return None

In [27]:
# input of 4x4 matrix
A = np.array([[10., -1.,   2.,  0.],
              [-1., 11.,  -1.,  3.],
              [ 2., -1.,  10., -1.],
              [ 0.,  3.,  -1.,  8.]])

b = np.array([6., 25., -11., 15.])

print('\nJacobi Iterative method : ')
jacobi_iterative(A,b)
print('\n*********************************************************************************************')
print('\nUsing the function for direct read numpy.linalg.solve():',np.linalg.solve(A, b))
print('\n*********************************************************************************************')


Jacobi Iterative method : 
Forming the eqn.:
10.0*x1 + -1.0*x2 + 2.0*x3 + 0.0*x4 = 6.0
-1.0*x1 + 11.0*x2 + -1.0*x3 + 3.0*x4 = 25.0
2.0*x1 + -1.0*x2 + 10.0*x3 + -1.0*x4 = -11.0
0.0*x1 + 3.0*x2 + -1.0*x3 + 8.0*x4 = 15.0

Iteration 1: [ 0.6   2.27 -1.1   1.88]
Iteration 2: [ 1.05  1.72 -0.81  0.89]
Iteration 3: [ 0.93  2.05 -1.05  1.13]
Iteration 4: [ 1.02  1.95 -0.97  0.97]
Iteration 5: [ 0.99  2.01 -1.01  1.02]
Iteration 6: [ 1.    1.99 -0.99  0.99]
Iteration 7: [ 1.  2. -1.  1.]
Iteration 8: [ 1.  2. -1.  1.]
Iteration 9: [ 1.  2. -1.  1.]
Iteration 10: [ 1.  2. -1.  1.]
Iteration 11: [ 1.  2. -1.  1.]
Iteration 12: [ 1.  2. -1.  1.]
Iteration 13: [ 1.  2. -1.  1.]
Iteration 14: [ 1.  2. -1.  1.]
Iteration 15: [ 1.  2. -1.  1.]
Iteration 16: [ 1.  2. -1.  1.]
Iteration 17: [ 1.  2. -1.  1.]
Iteration 18: [ 1.  2. -1.  1.]
Iteration 19: [ 1.  2. -1.  1.]
Iteration 20: [ 1.  2. -1.  1.]
Iteration 21: [ 1.  2. -1.  1.]
Iteration 22: [ 1.  2. -1.  1.]
Iteration 23: [ 1.  2. -1.  1.]
Itera

In [28]:
# Inputs of 5x5 Matrix
A = np. array([[11.,  3.,  0.,  1.,  2.],
               [ 0.,  4.,  2.,  0.,  1.],
               [ 3.,  2.,  7.,  1.,  0.],
               [ 4.,  0.,  4., 10.,  1.],
               [ 2.,  5.,  1.,  2., 13.]])

b = np. array([51., 15.,  15., 20., 92.])

print('\nJacobi Iterative method : ')
jacobi_iterative(A,b)
print('\n*********************************************************************************************')
print('\nUsing the function for direct read numpy.linalg.solve():',np.linalg.solve(A, b))
print('\n*********************************************************************************************')


Jacobi Iterative method : 
Forming the eqn.:
11.0*x1 + 3.0*x2 + 0.0*x3 + 1.0*x4 + 2.0*x5 = 51.0
0.0*x1 + 4.0*x2 + 2.0*x3 + 0.0*x4 + 1.0*x5 = 15.0
3.0*x1 + 2.0*x2 + 7.0*x3 + 1.0*x4 + 0.0*x5 = 15.0
4.0*x1 + 0.0*x2 + 4.0*x3 + 10.0*x4 + 1.0*x5 = 20.0
2.0*x1 + 5.0*x2 + 1.0*x3 + 2.0*x4 + 13.0*x5 = 92.0

Iteration 1: [4.64 3.75 2.14 2.   7.08]
Iteration 2: [ 2.15  0.91 -1.2  -1.42  4.45]
Iteration 3: [3.71 3.24 1.17 1.18 6.71]
Iteration 4: [ 2.43  1.49 -0.54 -0.62  4.99]
Iteration 5: [3.38 2.77 0.77 0.75 6.27]
Iteration 6: [ 2.67  1.8  -0.2  -0.28  5.32]
Iteration 7: [3.2  2.52 0.52 0.48 6.03]
Iteration 8: [ 2.81  1.98 -0.02 -0.09  5.5 ]
Iteration 9: [3.11 2.39 0.39 0.34 5.9 ]
Iteration 10: [2.88 2.08 0.08 0.01 5.6 ]
Iteration 11: [3.05 2.31 0.31 0.25 5.82]
Iteration 12: [2.92 2.14 0.14 0.07 5.66]
Iteration 13: [3.02 2.27 0.27 0.21 5.78]
Iteration 14: [2.95 2.17 0.17 0.11 5.69]
Iteration 15: [3.   2.24 0.24 0.18 5.76]
Iteration 16: [2.96 2.19 0.19 0.13 5.71]
Iteration 17: [2.99 2.23 0.23 0.1

----------------------------------------------------------------------------------------------------------------------------

Q5. Solve a system of equation by **Gauss Seidel iterative method**.
    
Verify if the equations are satisfied by your solutions using np.linalg.solve()

In [19]:
import numpy as np
def gauss_seidel(A,b,verbose=0,limit=1000):
    print("System of equations:")
    #np.set_printoptions(precision=2, suppress=True)
    for i in range(A.shape[0]):      # forming the eqn.
        row = ["{0:3g}*x{1}".format(A[i, j], j + 1) for j in range(A.shape[1])]
        print("{0} = {1:3g}".format(" + ".join(row), b[i]))    
    x = np.zeros_like(b)
    for it_count in range(1, limit):
        x_new = np.zeros_like(x)
        print("Iteration {0}: {1}".format(it_count, x))
        for i in range(A.shape[0]):
            s1 = np.dot(A[i, :i], x_new[:i])
            s2 = np.dot(A[i, i + 1 :], x[i + 1 :])
            x_new[i] = (b[i] - s1 - s2) / A[i, i]
        if np.allclose(x, x_new, rtol=1e-8):    # check for convergence
            break
        x = x_new
    print("Final output is :{0}".format(x))
    return None

In [22]:
# initialize the matrix
A = np.array([[10., -1.,   2.,  0.],
              [-1., 11.,  -1.,  3.],
              [ 2., -1.,  10., -1.],
              [ 0.,  3.,  -1.,  8.]])

b = np.array([6., 25., -11., 15.])

print('\nGauss Seidel iterative method : ')
gauss_seidel(A,b,i)
print('\n*********************************************************************************************')
print('\nUsing the function for direct read numpy.linalg.solve():',np.linalg.solve(A, b)) 
print('\n*********************************************************************************************')


Gauss Seidel iterative method : 
System of equations:
 10*x1 +  -1*x2 +   2*x3 +   0*x4 =   6
 -1*x1 +  11*x2 +  -1*x3 +   3*x4 =  25
  2*x1 +  -1*x2 +  10*x3 +  -1*x4 = -11
  0*x1 +   3*x2 +  -1*x3 +   8*x4 =  15
Iteration 1: [0. 0. 0. 0.]
Iteration 2: [ 0.6   2.33 -0.99  0.88]
Iteration 3: [ 1.03  2.04 -1.01  0.98]
Iteration 4: [ 1.01  2.   -1.    1.  ]
Iteration 5: [ 1.  2. -1.  1.]
Iteration 6: [ 1.  2. -1.  1.]
Iteration 7: [ 1.  2. -1.  1.]
Iteration 8: [ 1.  2. -1.  1.]
Iteration 9: [ 1.  2. -1.  1.]
Iteration 10: [ 1.  2. -1.  1.]
Final output is :[ 1.  2. -1.  1.]

*********************************************************************************************

Using the function for direct read numpy.linalg.solve(): [ 1.  2. -1.  1.]

*********************************************************************************************


In [23]:
# Inputs of 5x5 Matrix
A = np. array([[11.,  3.,  0.,  1.,  2.],
               [ 0.,  4.,  2.,  0.,  1.],
               [ 3.,  2.,  7.,  1.,  0.],
               [ 4.,  0.,  4., 10.,  1.],
               [ 2.,  5.,  1.,  2., 13.]])

b = np. array([51., 15.,  15., 20., 92.])

print('\nGauss Seidel iterative method : ')
gauss_seidel(A,b,i)
print('\n*********************************************************************************************')
print('\nUsing the function for direct read numpy.linalg.solve():',np.linalg.solve(A, b)) 
print('\n*********************************************************************************************')


Gauss Seidel iterative method : 
System of equations:
 11*x1 +   3*x2 +   0*x3 +   1*x4 +   2*x5 =  51
  0*x1 +   4*x2 +   2*x3 +   0*x4 +   1*x5 =  15
  3*x1 +   2*x2 +   7*x3 +   1*x4 +   0*x5 =  15
  4*x1 +   0*x2 +   4*x3 +  10*x4 +   1*x5 =  20
  2*x1 +   5*x2 +   1*x3 +   2*x4 +  13*x5 =  92
Iteration 1: [0. 0. 0. 0. 0.]
Iteration 2: [ 4.64  3.75 -0.92  0.51  4.91]
Iteration 3: [2.67 2.98 0.07 0.41 5.45]
Iteration 4: [2.8  2.35 0.21 0.25 5.69]
Iteration 5: [2.94 2.22 0.21 0.17 5.73]
Iteration 6: [2.97 2.21 0.21 0.15 5.73]
Iteration 7: [2.98 2.21 0.21 0.15 5.73]
Iteration 8: [2.98 2.21 0.21 0.15 5.73]
Iteration 9: [2.98 2.21 0.21 0.15 5.73]
Iteration 10: [2.98 2.21 0.21 0.15 5.73]
Iteration 11: [2.98 2.21 0.21 0.15 5.73]
Iteration 12: [2.98 2.21 0.21 0.15 5.73]
Iteration 13: [2.98 2.21 0.21 0.15 5.73]
Iteration 14: [2.98 2.21 0.21 0.15 5.73]
Final output is :[2.98 2.21 0.21 0.15 5.73]

*********************************************************************************************



----------------------------------------------------------------------------------------------------------------------------

Q6. Find the largest eigenvalue of **a real symmetric matric matrix by Power method**.    
$\\ \qquad\qquad$Verify if the equations are satisfied by your solutions using np.linalg.eig()

In [1]:
import numpy as np
def largest_eigenvalue_power_method(a):
    n= a.shape[0]
    def normalize(x):
        fac = abs(x).max()
        x_n = x / x.max()
        return fac, x_n
    x = np.ones(len(a))
    for i in range(2*len(a)**2):
        x = np.dot(a, x)
        lambda_1,x = normalize(x)
    print('Largest Eigenvalue is :',lambda_1)
    return None

In [2]:
#input 4x4 matrix
A = np.array([[ 2., 1., 2.],
              [ 1., 3., 2.],
              [ 2., 2., 1.]])
             
print("Power method for largest Eigenvalue:")
largest_eigenvalue_power_method(A)

x=np.linalg.eig(A)
print('\nusing the function for direct read np.linalg.eig(A):', x[0])             

Power method for largest Eigenvalue:
Largest Eigenvalue is : 5.387619058614335

using the function for direct read np.linalg.eig(A): [ 5.38761906  1.48645647 -0.87407553]


In [3]:
#input 4x4 matrix
A = np.array([[ 1., 5.,-3., 9.],
              [ 5., 0., 2.,-1.],
              [-3., 2., 8., 4.],
              [ 9.,-1., 4., 6.]])

print("Power method for largest Eigenvalue:")
largest_eigenvalue_power_method(A)

x=np.linalg.eig(A)
print('\nusing the function for direct read np.linalg.eig(A):', x[0]) 

Power method for largest Eigenvalue:
Largest Eigenvalue is : 13.74758682669266

using the function for direct read np.linalg.eig(A): [-9.87789801 13.74759325  9.06436433  2.06594043]


In [4]:
#input 5x5 matrix
A = np.array([[ 1.,-2., 0., 0., 0.],
              [-2.,-1., 3., 0., 0.],
              [ 0., 3., 0.,-1., 0.],
              [ 0., 0.,-1., 1., 4.],
              [ 0., 0., 0., 4., 3.]])

print("Power method for largest Eigenvalue:")
largest_eigenvalue_power_method(A)

x=np.linalg.eig(A)
print('\nusing the function for direct read np.linalg.eig(A):', x[0]) 

Power method for largest Eigenvalue:
Largest Eigenvalue is : 6.203178642447931

using the function for direct read np.linalg.eig(A): [-4.14518602 -2.13273178  0.71681796  3.3579212   6.20317864]
