## $$\text{Linear Algebra}$$

Q1.Using **Gauss elimination method** to form a upper triangulation of matrix .
       
And find the **determinant** by multiplying its diagonal and check using **$\text{np.linalg.det()}$**

In [1]:
import numpy as np
def gauss(a):
    m, n = a.shape               
    augment_mat = a
    np.set_printoptions(precision = 2, suppress = True)
    print('$ Original augment matrix $')
    print(augment_mat,'\n')
    print('# starting the elimination of matrix ') 
    
    for k in range(n):                        
        for j in range(k+1,n):                      
            q = float(augment_mat[j][k]) / augment_mat[k][k]  # lambda
            for m in range(k, n): 
                augment_mat[j][m] -=  q * augment_mat[k][m]
                 
    print('^^ this is the outstanding matrix from Gauss elimation ^^')           
    print(augment_mat,'\n')
    M = 1        
    for i in range(n):
        M *= augment_mat[i][i]
    print('Determinant of the matrix is :', M)
    return None

In [2]:
A = np. array([[ 1., 2.,-1., 1.],
               [-1., 1., 2.,-1.],
               [ 2.,-1., 2., 2.],
               [ 1., 1.,-1., 2.]])

print('\nGaussian elimination:  ')
gauss(A)
print('****************************************')
print('using np.linalg.det() :',np.linalg.det(A))
print('****************************************')


Gaussian elimination:  
$ Original augment matrix $
[[ 1.  2. -1.  1.]
 [-1.  1.  2. -1.]
 [ 2. -1.  2.  2.]
 [ 1.  1. -1.  2.]] 

# starting the elimination of matrix 
^^ this is the outstanding matrix from Gauss elimation ^^
[[ 1.    2.   -1.    1.  ]
 [ 0.    3.    1.    0.  ]
 [ 0.    0.    5.67  0.  ]
 [ 0.    0.    0.    1.  ]] 

Determinant of the matrix is : 17.0
****************************************
using np.linalg.det() : 17.0
****************************************


Q2.Using **Gauss elimination method** to solve a system of equation by **backward substitution** method 

And verify the output **$A.\text{X} = \text{b}$** and check using **$\text{np.linalg.solve()}$**.

In [3]:
import numpy as np
def gauss_elmbk(a, b):
    m, n = a.shape               
    b = b.reshape(n,1)
    augmented_mat = np.hstack((a,b))
    np.set_printoptions(precision = 2, suppress = True)
    print('$ Original augmented matrix $')
    print(augmented_mat,'\n')
    print('# starting the elimination of matrix ') 
    for k in range(n):                       
        for j in range(k+1,n):                      
            q = float(augmented_mat[j][k]) / augmented_mat[k][k]       # lambda
            for m in range(k, n+1):    # Forward Elimination - Subtracting rows
                augmented_mat[j][m] -=  q * augmented_mat[k][m] 
    print('^^ this is the outstanding augmented matrix from Gauss elimation ^^')           
    print(augmented_mat)

    x = np.zeros(n)
    print('\n# From Backwards Substitution:')      
    x[n-1] = float(augmented_mat[n-1][n]) / augmented_mat[n-1][n-1]  
    for i in range (n-1,-1,-1):                 # Backwards Substitution 
        z = 0.0                                     
        for j in range(i+1,n):                     
            z = z  + float(augmented_mat[i][j])*x[j]   
        x[i] = float(augmented_mat[i][n] - z) / augmented_mat[i][i]
        print('x[%i]='%(i+1),x[i])
    print('the desired values of X are :',x,'\n')    
    
    # checking if A.X == b :
    B = np.dot(a,x.reshape(n,1))
    print("B = ",B.reshape(1,n)[0])
    if (B[i] == b[i]): print("Yes! It's a match,i.e., A.X == b")
    else : print("No! Its not a matching,i.e., A.X != b")
    return None

In [4]:
A = np. array([[ 1., 2.,-1., 1.],
               [-1., 1., 2.,-1.],
               [ 2.,-1., 2., 2.],
               [ 1., 1.,-1., 2.]])

b = np. array([ 6., 3., 14., 8.])

print('\nGaussian elimination  and back substitution:')
gauss_elmbk(A, b)
print('**************************************************************')
print(' direct read using numpy.linalg.solve():',np.linalg.solve(A, b)) 
print('**************************************************************')


Gaussian elimination  and back substitution:
$ Original augmented matrix $
[[ 1.  2. -1.  1.  6.]
 [-1.  1.  2. -1.  3.]
 [ 2. -1.  2.  2. 14.]
 [ 1.  1. -1.  2.  8.]] 

# starting the elimination of matrix 
^^ this is the outstanding augmented matrix from Gauss elimation ^^
[[ 1.    2.   -1.    1.    6.  ]
 [ 0.    3.    1.    0.    9.  ]
 [ 0.    0.    5.67  0.   17.  ]
 [ 0.    0.    0.    1.    4.  ]]

# From Backwards Substitution:
x[4]= 4.0
x[3]= 3.0
x[2]= 2.0
x[1]= 1.0
the desired values of X are : [1. 2. 3. 4.] 

B =  [ 6.  3. 14.  8.]
Yes! It's a match,i.e., A.X == b
**************************************************************
 direct read using numpy.linalg.solve(): [1. 2. 3. 4.]
**************************************************************


Q3.Using **Gauss elimination method with pivot and backward substitution method** to solve a system of equation 

And verify the output **$A.\text{X} = \text{b}$** and check using **$\text{np.linalg.solve()}$**.

In [5]:
import numpy as np

def swaprows(v,i,j):
    if len(v.shape) == 1:
        v[i],v[j] = v[j],v[i]
    else:
        v[[i,j],:] = v[[j,i],:]  
        
def gauss_pivot(a, b):
    m, n = a.shape               
    b = b.reshape(n,1)
    augmented_mat = np.hstack((a,b))
    np.set_printoptions(precision = 2, suppress = True)
    print('$ Original augmented matrix $')
    print(augmented_mat,'\n')
    print('# starting the elimination of matrix ') 
    
    s = np.zeros(n)
    for i in range(n):
        s[i] = max(np.abs(augmented_mat[i,:]))
        
    for k in range(n):       
        p = np.argmax(np.abs(a[k:n,k])/s[k:n]) + k   # row interchange, if needed
        if p != k:
            swaprows(augmented_mat,k,p)
        for j in range(k+1,n):                      
            q = float(augmented_mat[j][k]) / augmented_mat[k][k]       # lambda
            for m in range(k, n+1):     # Forward Elimination - Subtracting rows
                augmented_mat[j][m] -=  q * augmented_mat[k][m] 
                #print(augmented_mat,'\n')    
                
    print('^^ this is the outstanding augmented matrix from Gauss elimation ^^')           
    print(augmented_mat,'\n')
    x = np.zeros(n)
    print('# From Backwards Substitution:')      
    x[n-1] =float(augmented_mat[n-1][n]) / augmented_mat[n-1][n-1]  
    for i in range (n-1,-1,-1):                         # Backwards Substitution         
        z = 0.0                                     
        for j in range(i+1,n):                     
            z = z  + float(augmented_mat[i][j])*x[j]   
        x[i] = float(augmented_mat[i][n] - z) / augmented_mat[i][i]
        print('x[%i]='%(i+1),x[i])
    print(' the desired values are :',x)    
    
    # checking if AX == b :
    B = np.dot(a,x.reshape(n,1))
    print("\nB = ",B.reshape(1,n)[0])
    if (B[i] == b[i]): print("Yes! It's a match,i.e., A.X == b")
    else : print("No! Its not a matching,i.e., A.X != b")
    return None             

In [6]:
A = np. array([[ 1., 2.,-1., 1.],
               [-1., 1., 2.,-1.],
               [ 2.,-1., 2., 2.],
               [ 1., 1.,-1., 2.]])

b = np. array([ 6., 3., 14., 8.])

print('Gaussian elimination (with Pivotting) and back substitution: ')
gauss_pivot(A, b)
print('**************************************************************')
print(' direct read using numpy.linalg.solve():',np.linalg.solve(A, b)) 
print('**************************************************************')

Gaussian elimination (with Pivotting) and back substitution: 
$ Original augmented matrix $
[[ 1.  2. -1.  1.  6.]
 [-1.  1.  2. -1.  3.]
 [ 2. -1.  2.  2. 14.]
 [ 1.  1. -1.  2.  8.]] 

# starting the elimination of matrix 
^^ this is the outstanding augmented matrix from Gauss elimation ^^
[[-1.    1.    2.   -1.    3.  ]
 [ 0.    3.    1.    0.    9.  ]
 [ 0.    0.    5.67  0.   17.  ]
 [ 0.    0.    0.    1.    4.  ]] 

# From Backwards Substitution:
x[4]= 4.0
x[3]= 3.0
x[2]= 2.0
x[1]= 1.0
 the desired values are : [1. 2. 3. 4.]

B =  [ 6.  3. 14.  8.]
Yes! It's a match,i.e., A.X == b
**************************************************************
 direct read using numpy.linalg.solve(): [1. 2. 3. 4.]
**************************************************************


Q4.Using **Gauss elimination method** find the **inverse of matrix** and verify **$A.A^{-1} = \text{I}$** and check using **$\text{np.linalg.inv()}$**

In [7]:
import numpy as np
def gauss_elmbk_matrix_inverse(a):
    m, n = a.shape               
    b = np.identity(len(a))
    augmented_mat = np.hstack((a,b))
    np.set_printoptions(precision = 2, suppress = True)
    print('$ Original augmented matrix $')
    print(augmented_mat,'\n')
    print('# starting the elimination of matrix ') 
    for k in range(n+len(a)):                  
        for j in range(k+1,n):                      
            q = float(augmented_mat[j][k]) / augmented_mat[k][k]        # lambda
            for m in range(k, n+len(a)): # Forward Elimination - Subtracting rows 
                augmented_mat[j][m] -=  q * augmented_mat[k][m]  
    print('^^ this is the outstanding augmented matrix from Gauss elimation ^^')           
    print(augmented_mat,'\n')
    x = np.zeros(n)
    print('# From Backwards Substitution:') 
    for i in range(0, n):
        pivot = augmented_mat[i][i]            # select pivot value
        row   = augmented_mat[i]               # extract row
        augmented_mat[i] = row / pivot         # gets 1 along the diagonal
        for j in [k for k in range(0, n) if k != i]:
            augmented_mat[j] = augmented_mat[j] - augmented_mat[i] * augmented_mat[j][i]
    print(augmented_mat)
    print('\nInverse Matrix') 
    print(augmented_mat[:, n:])
        
    # check A.A⁻¹ == I
    print('\n# Product of of original and inverse matrix,i.e.,  A.A⁻¹ : ')
    B=np.dot(a,augmented_mat[:, n:])
    print(B)
    if(abs(B[j][i]) == b[j][i]): print('Yes! Its an identity, i.e., A.A\u207B\u00B9 == I')
    else : print('No! Its not an identity , i.e., A.A\u207B\u00B9 != I') 
    return None

In [8]:
A = np. array([[ 1., 2.,-1., 1.],
               [-1., 1., 2.,-1.],
               [ 2.,-1., 2., 2.],
               [ 1., 1.,-1., 2.]])
print('\nGauss elimination method of matrix inverse: ')
gauss_elmbk_matrix_inverse(A)
print('******************************************************')
print('Using the function for direct read numpy.linalg.inv():')
print(np.linalg.inv(A))
print('******************************************************')


Gauss elimination method of matrix inverse: 
$ Original augmented matrix $
[[ 1.  2. -1.  1.  1.  0.  0.  0.]
 [-1.  1.  2. -1.  0.  1.  0.  0.]
 [ 2. -1.  2.  2.  0.  0.  1.  0.]
 [ 1.  1. -1.  2.  0.  0.  0.  1.]] 

# starting the elimination of matrix 
^^ this is the outstanding augmented matrix from Gauss elimation ^^
[[ 1.    2.   -1.    1.    1.    0.    0.    0.  ]
 [ 0.    3.    1.    0.    1.    1.    0.    0.  ]
 [ 0.    0.    5.67  0.   -0.33  1.67  1.    0.  ]
 [ 0.    0.    0.    1.   -0.65  0.24 -0.06  1.  ]] 

# From Backwards Substitution:
[[ 1.    0.    0.    0.    0.88 -0.41  0.35 -1.  ]
 [ 0.    1.    0.    0.    0.35  0.24 -0.06  0.  ]
 [ 0.    0.    1.    0.   -0.06  0.29  0.18  0.  ]
 [ 0.    0.    0.    1.   -0.65  0.24 -0.06  1.  ]]

Inverse Matrix
[[ 0.88 -0.41  0.35 -1.  ]
 [ 0.35  0.24 -0.06  0.  ]
 [-0.06  0.29  0.18  0.  ]
 [-0.65  0.24 -0.06  1.  ]]

# Product of of original and inverse matrix,i.e.,  A.A⁻¹ : 
[[ 1.  0.  0.  0.]
 [-0.  1. -0.  0.]
 [ 0.  0

In [9]:
A = np. array([[ 2.,  0.,  0.,  0.],
               [ 2.,  2.,  0.,  0.],
               [ 2.,  4.,  2.,  0.],
               [ 2.,  6.,  6.,  2.]])

print('\nGauss elimination method of matrix inverse: ')
gauss_elmbk_matrix_inverse(A)
print('******************************************************')
print('Using the function for direct read numpy.linalg.inv():')
print(np.linalg.inv(A))
print('******************************************************')


Gauss elimination method of matrix inverse: 
$ Original augmented matrix $
[[2. 0. 0. 0. 1. 0. 0. 0.]
 [2. 2. 0. 0. 0. 1. 0. 0.]
 [2. 4. 2. 0. 0. 0. 1. 0.]
 [2. 6. 6. 2. 0. 0. 0. 1.]] 

# starting the elimination of matrix 
^^ this is the outstanding augmented matrix from Gauss elimation ^^
[[ 2.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  2.  0.  0. -1.  1.  0.  0.]
 [ 0.  0.  2.  0.  1. -2.  1.  0.]
 [ 0.  0.  0.  2. -1.  3. -3.  1.]] 

# From Backwards Substitution:
[[ 1.   0.   0.   0.   0.5  0.   0.   0. ]
 [ 0.   1.   0.   0.  -0.5  0.5  0.   0. ]
 [ 0.   0.   1.   0.   0.5 -1.   0.5  0. ]
 [ 0.   0.   0.   1.  -0.5  1.5 -1.5  0.5]]

Inverse Matrix
[[ 0.5  0.   0.   0. ]
 [-0.5  0.5  0.   0. ]
 [ 0.5 -1.   0.5  0. ]
 [-0.5  1.5 -1.5  0.5]]

# Product of of original and inverse matrix,i.e.,  A.A⁻¹ : 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Yes! Its an identity, i.e., A.A⁻¹ == I
******************************************************
Using the function for direct read 

Q5.Using **Gauss Jordan elimination** to solve a system of equation 

And verify the output **$A.\text{X} = \text{b}$** and check using **$\text{np.linalg.solve()}$**.

In [10]:
import numpy as np
def gauss_jordan(a, b):
    m, n = a.shape               
    b = b.reshape(n,1)
    augmented_mat = np.hstack((a,b))
    np.set_printoptions(precision = 2, suppress = True)
    print('$ Original augmented matrix $')
    print(augmented_mat,'\n')
    outer_loop = [[0, m - 1, 1], [m - 1, 0, -1]]
    for d in range(2):
        for i in range(outer_loop[d][0], outer_loop[d][1], outer_loop[d][2]):
            inner_loop = [[i + 1, m, 1], [i - 1, -1, -1]]
            for j in range(inner_loop[d][0], inner_loop[d][1], inner_loop[d][2]):
                k = (-1) * augmented_mat[j, i] / augmented_mat[i, i]
                temp_row = augmented_mat[i, :] * k
                augmented_mat[j, :] += temp_row
    for i in range(0, m):
        augmented_mat[i, :] = augmented_mat[i, :] / augmented_mat[i, i]
    print('# Normalizing the rows')
    print(augmented_mat)
    print('\nThe desired values of X are :',augmented_mat[:, n] ,'\n')    
    
    # checking if A.X == b :
    B = np.dot(a,augmented_mat[:, n].reshape(n,1))
    print("B = ",B.reshape(1,n)[0])
    if(B[i] == b[i]): print("Yes! It's a match,i.e., A.X == b")
    else : print("No! Its not a matching,i.e., A.X != b")
    return None

In [11]:
A = np.array([[10., -1.,   2.,  0.],
              [-1., 11.,  -1.,  3.],
              [ 2., -1.,  10., -1.],
              [ 0.,  3.,  -1.,  8.]])

b = np.array([6., 25., -11., 15.])

print(' Gauss Jordan elimination: ')
gauss_jordan(A, b)
print('*************************************************************')
print('direct read using numpy.linalg.solve():',np.linalg.solve(A, b))
print('*************************************************************')

 Gauss Jordan elimination: 
$ Original augmented matrix $
[[ 10.  -1.   2.   0.   6.]
 [ -1.  11.  -1.   3.  25.]
 [  2.  -1.  10.  -1. -11.]
 [  0.   3.  -1.   8.  15.]] 

# Normalizing the rows
[[ 1. -0. -0.  0.  1.]
 [ 0.  1. -0.  0.  2.]
 [ 0. -0.  1.  0. -1.]
 [ 0. -0.  0.  1.  1.]]

The desired values of X are : [ 1.  2. -1.  1.] 

B =  [  6.  25. -11.  15.]
Yes! It's a match,i.e., A.X == b
*************************************************************
direct read using numpy.linalg.solve(): [ 1.  2. -1.  1.]
*************************************************************


Q6. Using **Gauss Jordan elimination** find the **inverse of matrix** and verify **$A.A^{-1} = \text{I}$** and check using **$\text{np.linalg.inv()}$**

In [12]:
import numpy as np
def gauss_jordan_matrix_inverse(a):
    m, n = a.shape              
    b = np.identity(len(a))
    augmented_mat = np.hstack((a,b))
    np.set_printoptions(precision = 2, suppress = True)
    print('$ Original augmented matrix $')
    print(augmented_mat)
    outer_loop = [[0, m - 1, 1], [m - 1, 0, -1]]
    for d in range(2):
        for i in range(outer_loop[d][0], outer_loop[d][1], outer_loop[d][2]):
            inner_loop = [[i + 1, m, 1], [i - 1, -1, -1]]
            for j in range(inner_loop[d][0], inner_loop[d][1], inner_loop[d][2]):
                k = (-1) * augmented_mat[j, i] / augmented_mat[i, i]
                temp_row = augmented_mat[i, :] * k
                augmented_mat[j, :] += temp_row
    for i in range(0, m):
        augmented_mat[i, :] = augmented_mat[i, :] / augmented_mat[i, i]
    print('\n# Normalizing the rows')
    print(augmented_mat)   
    print('\nINVERSE MATRIX IS:') 
    print(augmented_mat[:, n:])
    
    # check A.A⁻¹ == I
    print('\n#product of of original and inverse matrix ')
    B = np.dot(a,augmented_mat[:, n:])
    print(B) 
    if(abs(B[j][i]) == b[j][i]): print('Yes! Its an identity, i.e., A.A\u207B\u00B9 == I')
    else : print('No! Its not an identity , i.e., A.A\u207B\u00B9 != I') 
    return None

In [13]:
A = np. array([[ 1., 2.,-1., 1.],
               [-1., 1., 2.,-1.],
               [ 2.,-1., 2., 2.],
               [ 1., 1.,-1., 2.]])
print('Gauss Jordan method of matrix inverse: ')
gauss_jordan_matrix_inverse(A)
print('***************************************')
print(' direct read using numpy.linalg.inv(): ')
print(np.linalg.inv(A))
print('***************************************')

Gauss Jordan method of matrix inverse: 
$ Original augmented matrix $
[[ 1.  2. -1.  1.  1.  0.  0.  0.]
 [-1.  1.  2. -1.  0.  1.  0.  0.]
 [ 2. -1.  2.  2.  0.  0.  1.  0.]
 [ 1.  1. -1.  2.  0.  0.  0.  1.]]

# Normalizing the rows
[[ 1.    0.    0.    0.    0.88 -0.41  0.35 -1.  ]
 [ 0.    1.    0.    0.    0.35  0.24 -0.06  0.  ]
 [ 0.    0.    1.    0.   -0.06  0.29  0.18  0.  ]
 [ 0.    0.    0.    1.   -0.65  0.24 -0.06  1.  ]]

INVERSE MATRIX IS:
[[ 0.88 -0.41  0.35 -1.  ]
 [ 0.35  0.24 -0.06  0.  ]
 [-0.06  0.29  0.18  0.  ]
 [-0.65  0.24 -0.06  1.  ]]

#product of of original and inverse matrix 
[[ 1.  0.  0.  0.]
 [ 0.  1. -0.  0.]
 [-0.  0.  1.  0.]
 [ 0.  0. -0.  1.]]
Yes! Its an identity, i.e., A.A⁻¹ == I
***************************************
 direct read using numpy.linalg.inv(): 
[[ 0.88 -0.41  0.35 -1.  ]
 [ 0.35  0.24 -0.06  0.  ]
 [-0.06  0.29  0.18  0.  ]
 [-0.65  0.24 -0.06  1.  ]]
***************************************


In [14]:
A = np. array([[ 2.,  0.,  0.,  0.],
               [ 2.,  2.,  0.,  0.],
               [ 2.,  4.,  2.,  0.],
               [ 2.,  6.,  6.,  2.]])

print('Gauss Jordan method of matrix inverse: ')
gauss_jordan_matrix_inverse(A)
print('***************************************')
print(' direct read using numpy.linalg.inv(): ')
print(np.linalg.inv(A))
print('***************************************')

Gauss Jordan method of matrix inverse: 
$ Original augmented matrix $
[[2. 0. 0. 0. 1. 0. 0. 0.]
 [2. 2. 0. 0. 0. 1. 0. 0.]
 [2. 4. 2. 0. 0. 0. 1. 0.]
 [2. 6. 6. 2. 0. 0. 0. 1.]]

# Normalizing the rows
[[ 1.   0.   0.   0.   0.5  0.   0.   0. ]
 [ 0.   1.   0.   0.  -0.5  0.5  0.   0. ]
 [ 0.   0.   1.   0.   0.5 -1.   0.5  0. ]
 [ 0.   0.   0.   1.  -0.5  1.5 -1.5  0.5]]

INVERSE MATRIX IS:
[[ 0.5  0.   0.   0. ]
 [-0.5  0.5  0.   0. ]
 [ 0.5 -1.   0.5  0. ]
 [-0.5  1.5 -1.5  0.5]]

#product of of original and inverse matrix 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Yes! Its an identity, i.e., A.A⁻¹ == I
***************************************
 direct read using numpy.linalg.inv(): 
[[ 0.5  0.   0.   0. ]
 [-0.5  0.5  0.   0. ]
 [ 0.5 -1.   0.5 -0. ]
 [-0.5  1.5 -1.5  0.5]]
***************************************


Q7. Using **Jacobi iterative method** to solve a system of equation 

And verify the output **$A.\text{X} = \text{b}$** and check using **$\text{np.linalg.solve()}$**.

In [15]:
import numpy as np
def jacobi_iterative(a,b,limit = 100):
    m,n = a.shape
    print("Forming the system.:")             # prints the system
    np.set_printoptions(precision = 2, suppress = True)    
    for i in range(a.shape[0]):      # forming the eqn.
        row = ["{0:3g}*x{1}".format(a[i, j], j + 1) for j in range(a.shape[1])]
        print("{0} = {1:3g}".format(" + ".join(row), b[i]))    
    x = np.zeros_like(b)
    for it_count in range(limit+1):   
        x_new = np.zeros_like(x)
        for i in range(a.shape[0]):
            s1 = np.dot(a[i, :i], x[:i])
            s2 = np.dot(a[i, i + 1:], x[i + 1:])
            x_new[i] = (b[i] - s1 - s2) / a[i, i]
            if x_new[i] == x_new[i-1]:   # check for convergence
                break
        if np.allclose(x, x_new, atol=1e-10, rtol=0.):
            break
        x = x_new
        #print("Iteration {%i}: "%(it_count), x)
    print('Final output of x is :',x,'after {%i} count'%(it_count))
    
    # checking if A.X == b :
    x = x.reshape(n,1)
    B = np.round(np.dot(a,x).reshape(1,n)[0],2)
    print('\nB =',B)
    if(b[i] == B[i]): print('Yes! its a match,i.e., A.X == b ')
    else : print('No! its not a match,i.e., A.X != b ')
    return None

In [16]:
A = np.array([[10., -1.,   2.,  0.],
              [-1., 11.,  -1.,  3.],
              [ 2., -1.,  10., -1.],
              [ 0.,  3.,  -1.,  8.]])

b = np.array([6., 25., -11., 15.])

print('\nJacobi Iterative method : ')
jacobi_iterative(A,b)
print('**************************************************************')
print(' direct read using numpy.linalg.solve():',np.linalg.solve(A, b))
print('**************************************************************')


Jacobi Iterative method : 
Forming the system.:
 10*x1 +  -1*x2 +   2*x3 +   0*x4 =   6
 -1*x1 +  11*x2 +  -1*x3 +   3*x4 =  25
  2*x1 +  -1*x2 +  10*x3 +  -1*x4 = -11
  0*x1 +   3*x2 +  -1*x3 +   8*x4 =  15
Final output of x is : [ 1.  2. -1.  1.] after {28} count

B = [  6.  25. -11.  15.]
Yes! its a match,i.e., A.X == b 
**************************************************************
 direct read using numpy.linalg.solve(): [ 1.  2. -1.  1.]
**************************************************************


Q8.Using **Gauss Seidel iterative method** to solve a system of equation 
    
And verify the output **$A.\text{X} = \text{b}$** and check using **$\text{np.linalg.solve()}$**.

In [17]:
import numpy as np
def gauss_seidel(a,b,limit=1000):
    m,n = a.shape
    print("System of equations:")
    np.set_printoptions(precision=2, suppress=True)
    for i in range(a.shape[0]):      # forming the eqn.
        row = ["{0:3g}*x{1}".format(a[i, j], j + 1) for j in range(a.shape[1])]
        print("{0} = {1:3g}".format(" + ".join(row), b[i]))    
    x = np.zeros_like(b)
    for it_count in range(1, limit):
        x_new = np.zeros_like(x)
        for i in range(a.shape[0]):
            s1 = np.dot(a[i, :i], x_new[:i])
            s2 = np.dot(a[i, i + 1 :], x[i + 1 :])
            x_new[i] = (b[i] - s1 - s2) / a[i, i]
        if np.allclose(x, x_new, rtol=1e-8):    # check for convergence
            break
        x = x_new
    print("\nFinal output X is :",x,"after {%i} counts"%(it_count))
    
    # check if A.X == b:
    B = np.dot(a,x.reshape(n,1))
    print('\nB = ',B.reshape(1,n)[0])
    if(b[i] == B[i]) : print('Yes! its a match,i.e., A.X == b ')
    else : print('No! its not a match,i.e., A.X != b ')
    return None

In [18]:
A = np.array([[10., -1.,   2.,  0.],
              [-1., 11.,  -1.,  3.],
              [ 2., -1.,  10., -1.],
              [ 0.,  3.,  -1.,  8.]])

b = np.array([6., 25., -11., 15.])

print('\nGauss Seidel method : ')
gauss_seidel(A,b)
print('**************************************************************')
print(' direct read using numpy.linalg.solve():',np.linalg.solve(A, b))
print('**************************************************************')


Gauss Seidel method : 
System of equations:
 10*x1 +  -1*x2 +   2*x3 +   0*x4 =   6
 -1*x1 +  11*x2 +  -1*x3 +   3*x4 =  25
  2*x1 +  -1*x2 +  10*x3 +  -1*x4 = -11
  0*x1 +   3*x2 +  -1*x3 +   8*x4 =  15

Final output X is : [ 1.  2. -1.  1.] after {10} counts

B =  [  6.  25. -11.  15.]
Yes! its a match,i.e., A.X == b 
**************************************************************
 direct read using numpy.linalg.solve(): [ 1.  2. -1.  1.]
**************************************************************


Q9.Find the largest eigenvalue  and corresponding eigenvectors of matrix by **Power method** 

And check the output with direct method using np.linalg.eig()

In [19]:
import  numpy as np
np.set_printoptions(precision = 2, suppress = True)
def largest_eigenvalue_power(M,tol):    
    X = np.ones(len(M))
    den = (X.T).dot(X)
    Y = M.dot(X)
    c,lambda_0,d = 0,0,1
    while abs(d) > tol:
        c += 1
        num = (X.T).dot(Y)
        lambda_1 = num / den
        d = lambda_1 - lambda_0
        lambda_0 = lambda_1
        den = num
        Y = M.dot(Y)
    print('Eigen Value, \u03BB : %0.2f'%lambda_1)
    print('Eigen Vector :',Y / np.linalg.norm(Y)) 
    return None

In [20]:
M = np.array([[   4., 2/3., -4/3., 4/3.],
              [ 2/3.,   4.,    0.,   0.],
              [-4/3.,   0.,    6.,   2.],
              [ 4/3.,   0.,    2.,   6.]])

print('Power Method')
largest_eigenvalue_power(M,0.00001)
print('*****************************************')
print('direct read using np.linalg.eig()')
e,V=np.linalg.eig(M)
print('Eigen Values, \u03BB :',e,'\nEigen Vectors:')
print(V)

Power Method
Eigen Value, λ : 8.00
Eigen Vector : [0.   0.   0.71 0.71]
*****************************************
direct read using np.linalg.eig()
Eigen Values, λ : [2. 6. 4. 8.] 
Eigen Vectors:
[[-0.71  0.71  0.   -0.  ]
 [ 0.24  0.24 -0.94 -0.  ]
 [-0.47 -0.47 -0.24  0.71]
 [ 0.47  0.47  0.24  0.71]]


Q10.Find the smallest eigenvalue  and corresponding eigenvectors of matrix by **Inverse Power method** 

And compare the inverse of eigen value λ⁻¹ with the original matrix eigen value λ and also from np.linalg.eig()

In [21]:
import  numpy as np
np.set_printoptions(precision = 2, suppress = True)
def smallest_eigenvalue_power(M,tol):    
    M_inv = np.linalg.inv(M)
    X = np.ones(len(M_inv))
    den = (X.T).dot(X)
    Y = M_inv.dot(X)
    c,lambda_0,d = 0,0,1
    while abs(d) > tol:
        c += 1
        num = (X.T).dot(Y)
        lambda_1 = num / den
        d = lambda_1 - lambda_0
        lambda_0 = lambda_1
        den = num
        Y = M_inv.dot(Y)
    print('Inverse Eigen Value, \u03BB\u207B\u00B9 : %0.2f'%lambda_1)
    print('Corresponding Eigen Value, \u03BB : %0.2f'%(1/lambda_1)) 
    print('Inverse Eigen Vector :',Y / np.linalg.norm(Y)) 
    return None

In [22]:
M = np.array([[   4., 2/3., -4/3., 4/3.],
              [ 2/3.,   4.,    0.,   0.],
              [-4/3.,   0.,    6.,   2.],
              [ 4/3.,   0.,    2.,   6.]])

print('Inverse Power Method')
smallest_eigenvalue_power(M,0.000001)
print('*****************************************************')
print('direct read using np.linalg.eig()')
e,V = np.linalg.eig(M)
print('Eigen Values of original Matrix, \u03BB :',e)
einv,Vinv=np.linalg.eig(np.linalg.inv(M))
print('Inverse Eigen Values, \u03BB\u207B\u00B9 :',einv,'\nInverse Eigen Vectors:')
print(Vinv)

Inverse Power Method
Inverse Eigen Value, λ⁻¹ : 0.50
Corresponding Eigen Value, λ : 2.00
Inverse Eigen Vector : [ 0.71 -0.24  0.47 -0.47]
*****************************************************
direct read using np.linalg.eig()
Eigen Values of original Matrix, λ : [2. 6. 4. 8.]
Inverse Eigen Values, λ⁻¹ : [0.17 0.5  0.25 0.12] 
Inverse Eigen Vectors:
[[-0.71 -0.71 -0.    0.  ]
 [-0.24  0.24 -0.94 -0.  ]
 [ 0.47 -0.47 -0.24  0.71]
 [-0.47  0.47  0.24  0.71]]
