In [1]:
import numpy as np

What is the mean and variance of the Gaussian distribution function : $P(x)=\frac{1}{\sqrt{2\pi}}\exp\left(-\frac{x^2}{2}+x-2\right)?$                                                                                                                                                                                                     
Ans :- To find the mean and variance of a probability distribution represented by a Gaussian (normal) distribution function,                                                                                                                                         
we need to consider the standard form of the Gaussian distribution :                                                                                                                                                                    
$\qquad P(x) = \frac{1}{\sqrt{2\pi}\sigma} \exp\left(-\frac{(x-\mu)^2}{2\sigma^2}\right)  = 
\frac{1}{\sqrt{2\pi}\sigma} \exp\left(-\frac{(x^2-2\mu x + \mu^2)}{2\sigma^2}\right) =
\frac{1}{\sqrt{2\pi}\sigma} \exp\left(\frac{(-x^2+2\mu x - \mu^2)}{2\sigma^2}\right) =
\frac{1}{\sqrt{2\pi}\sigma} \exp\left(-\frac{x^2}{2\sigma^2}+\frac{\mu x}{\sigma^2} - \frac{\mu^2}{2\sigma^2}\right)$                                       
In this standard form,                                                                                                      
$\mu$ represents the mean (average) of the distribution,                                                                    
and $\sigma^2$ represents the variance (the square of the standard deviation).                                                                                                                                                                     
In our provided distribution function, $P(x) = \frac{1}{\sqrt{2\pi}} \exp\left(-\frac{x^2}{2}+2x-2\right)$,               
we can see that it matches the standard form with some adjustments.                                                                                                                                                                      
Comparing the two equations, the mean of the distribution is 2, and the variance is 1.

What is the upper triangular matrix in the LU decomposition of the given matrix?                                                
$\qquad \begin{bmatrix} 3 & 2 & 4 \\ 2 & 0 & 2 \\ 4 & 2 & 3 \end{bmatrix}$                                                      
Note: use lu function from scipy.linalg module for this.

In [2]:
A = np.array([[3, 2, 4],
              [2, 0, 2],
              [4, 2, 3]])

from scipy.linalg import lu
P, L, U = lu(A)

U

array([[ 4. ,  2. ,  3. ],
       [ 0. , -1. ,  0.5],
       [ 0. ,  0. ,  2. ]])

For a square matrix how are the trace and determinant related to eigenvalues?

In [3]:
A = np.array([[3, 2, 4],
              [2, 0, 2],
              [4, 2, 3]])

l = np.linalg.eigvals(A)

det_l   = np.prod(l)                   # Determinant = product of eigenvalues
trace_l = np.sum(l)                    # Trace = sum of eigenvalues
det_A   = np.linalg.det(A)
trace_A = np.trace(A)

round(det_l,2), round(det_A,2), round(trace_l,2), round(trace_A,2)

(8.0, 8.0, 6.0, 6)

Which function in numpy module can be used to fit polynomials to a given data points?

In [4]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([1, 4, 9, 16, 25])

np.polyfit(x, y, 2)

array([ 1.00000000e+00, -2.00147285e-14,  3.55405155e-14])

Calculate the integral  $\int^1_0 \text{tanh}^2(x^2) \ dx$ using Monte Carlo method.                                            
Use $N = 1000000$ random points. What is the value of the integral rounded to two decimal places?

In [5]:
def f(x):
    return (np.tanh(x**2))**2

N = 1000000
count = 0

for i in range(N):
    x = np.random.rand()          # Generate a random x between 0 and 1
    y = np.random.rand()          # Generate a random y between 0 and max_y
    if y <= f(x):
        count += 1

I = count/N
round(I, 2)

0.15

Solve the following equations using solve function from numpy.linalg module:                                                 
$\qquad\qquad 4x  + 7y + 5z  =  2$                                                                                                                
$\qquad\qquad \ \ x - \ \ y    + 3z  = 10$                                                                                                          
$\qquad\qquad 5x  - \ \ y    + 2z  = 15$                                                                                       
Let $x_0, y_0, z_0$ be the solution and let $s = x_0 + y_0 + z_0$. What is the value of $s$ rounded to two decimal places?

In [6]:
A = np.array([[ 4, 7, 5],
              [ 1,-1, 3],
              [ 5,-1, 2]])

b = np.array([2, 10, 15])
x0, y0, z0 = np.linalg.solve(A, b)
s = x0 + y0 + z0
round(s, 2)

1.62

Find the eigen values of the following matrix using the eigvals function from numpy.linalg library                                  
 $ \qquad\begin{bmatrix} 2.15 & 1 & 2 \\ 1 & 2.98 & 2 \\ 2.22 & 2 & 1 \end{bmatrix}$                                                   
 Let A be the sum of eigenvalues and B be the product of eigenvalues.                                                        
 Now define                                                                                                                 
 $\qquad\qquad e=\frac{B−A}{B}$                           
What is the value of  e rounded to 4 decimal places?                                                                        
Note: use np.sum and np.prod to find the sum and product of eigenvalues.

In [7]:
E = np.array([[ 2.15, 1.00, 2.00],
              [ 1.00, 2.98, 2.00],
              [ 2.22, 2.00, 1.00]])

l = np.linalg.eigvals(E)
A = np.sum(l)
B = np.prod(l)
e = (B-A)/B
round(e, 4)

1.7678

Find the eigenvalues and determinant of the following matrix using the eigvals and det functions from the numpy.linalg library.                                                                                                                    
 $\qquad \begin{bmatrix} 1 & 2 & 3 \\ 2 & 1 & 4 \\ 3 & 4 & 2 \end{bmatrix}$                                                   
Now calculate the product of eigenvalues and let it be $\det_A$. And let $\det_B$ be the value of  determinant that you got by using det function from numpy.linalg.                                                                                                 
Now define                                                                                                                   
$\qquad\qquad e=\frac{\det_B-\det_A}{\det_B}∗10^{16}$                                                                        
What is the value of e rounded to four decimal places?                                                                          
Note: use np.prod to calculate the product of eigenvalues.

In [8]:
E = np.array([[ 1, 2, 3],
              [ 2, 1, 4],
              [ 3, 4, 2]])

l = np.linalg.eigvals(E)

det_A = np.prod(l)
det_B = np.linalg.det(E)
e = (det_B-det_A)/det_B * 1e16
round(e, 4)

2.0898

Calculate the integral $\int^1_0 \cos^2 \left(\frac{1}{x(1−x)} \right) \ dx$   using Monte Carlo method.                   
Use $N = 1000000$ random points. Let $A$ be the value of integral using monte carlo method.                                         
Now define $\quad e = 1 - A$                                                                                                   
What is the value of e rounded to one decimal place?

In [9]:
def f(x):
    return (np.cos(1/(x*(1-x))))**2

N = 1000000
count = 0
for i in range(N):
    x = np.random.rand()
    y = np.random.rand()
    if y<f(x):
        count += 1
        
A = count/N
e = 1-A
round(e,1)

0.6

Find the eigenvalues and eigenvectors of the following matrix using eig function from numpy.linalg module                      
 $\qquad \begin{bmatrix} 1.9 & -1 & 0 \\ 3 & -2 & 1 \\ 0 & 1 & 3 \end{bmatrix}$                                                   
Let A be the eigenvector corresponding to the maximum eigenvalue. What is the value of A rounded to two decimal places?

In [10]:
E = np.array([[ 1.9, -1, 0],
              [ 3.0, -2, 1],
              [ 0.0,  1, 3]])

l, x = np.linalg.eig(E)
np.round(l,2), np.round(x,2)

(array([-1.29,  1.06,  3.13]),
 array([[ 0.29, -0.73, -0.11],
        [ 0.93, -0.61,  0.13],
        [-0.22,  0.31,  0.99]]))